### ISSUE TITLE
Readme.md 수정 필요 (안드로이드 설치방법)

### ISSUE THREAD

**Issue by marsinearth** [react-native-seoul/react-native-kakao-login#100]
### Version of kakao-login libraries

2.2.0

### Version of react-native

0.61.5

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

컴파일 됨

### Actual behavior

<img width="549" alt="스크린샷 2020-02-05 오후 10 59 38" src="https://user-images.githubusercontent.com/6101260/73848310-38ced100-486b-11ea-9341-76eeccc6f097.png">

### Tested environment (Emulator? Real Device?)

Android Q Pixel 3 API 29 에서 발생합니다. ReadMe의 Android 인스톨 설명 부분에서 MainApplication.java 부분의 `packages.add(new RNKakaoLoginsPackage());` 를 지우니까 해결 되었습니다. `import com.dooboolab.kakaologins.RNKakaoLoginsPackage;` 와 중복처리나는것 같습니다.

**Comment by heyman333** [comment]
@marsinearth 혹시 의도적으로 수동으로 설치 하신건가요? 처음부터 autoLink를 염두해 두시고 설치 하셨다면 원래  `packages.add(new RNKakaoLoginsPackage())`를 실행하실 필요가 없습니다

**Comment by marsinearth** [comment]
iOS 와 Android 설정이 Manual Installation에 종속되는 거였군요! 인덴테이션이 되어 있지 않아서 좀 헷갈렸네요;

**Comment by heyman333** [comment]
@marsinearth 🙌🙌🙌🙌🙌
