### ISSUE TITLE
iOS에서 'React/RCTBridgeModule.h' file not found 

### ISSUE THREAD

**Issue by XOneto9** [react-native-seoul/react-native-kakao-login#107]
카카오 오그인 라이브러리: 1.20.0, 1.21.1 (둘다 해봤는데 같은 오류..)
리엑트네이티브: sdk-36.0.1 
expo 사용: 36.0.0
expo-kit : 36.0.1

문제 platform: iOS
현재 xcode에서 빌드 자체가 안되고 있습니다.

앞서 오류를 찾아보았지만 딱히 답이 없어보이네요.
제가 어디서 잘 못한건지 알기가 어렵네요..
'React/RCTBridgeModule.h' file not found
이 에러가 뜹니다..

iOS install은 pods을 사용했습니다.

또한 RNKakaoLogins.xcodeproj 추가j는 react-native(프로젝트 최상위 루트)에서 node_modules폴더로 이동후 yarn으로 다운 받은 react-native-kakao-login(해당 모듈) =>react-native-seoul/kakao-login => iOS => RNKakaoLogins.xcodeproj 에서 추가 하였습니다.

한가지 더 궁금한 점은 ReadMe.md에 post installation 에서
Project => Targets 아래 앱 선택 => General 탭으로 이동해서 Bundle Identifier가 본인의 카카오 앱과 동일한지 확인해주세요.

여기서 project는 어떤걸 의미 하나요? react-native에서 나온 ios의 project가 맞는지요?

![스크린샷 2020-03-15 오전 4 31 37](https://user-images.githubusercontent.com/18350072/76689057-df31a180-6675-11ea-9288-405004e69a27.png)

![스크린샷 2020-03-15 오전 4 29 18](https://user-images.githubusercontent.com/18350072/76689026-9b3e9c80-6675-11ea-8b09-e91e910c82c3.png)

조언을 부탁드립니다.

**Comment by XOneto9** [comment]
- 자답변 남깁니다.

간혹 xcode에서 RNKakaoLogins.xcodeproj와 같이 외부 라이브러리를 추가 할때, 해당 파일이 복사가 되지 않고 참조만 되는 경우가 있습니다.

참조가 되서 그런것 같아요. 실제 파일을 경로에 넣어주니 작동을 하는 것 같습니다..
현재까지는 그렇다고 추축 되네요.

**Comment by heyman333** [comment]
카카오 로그인 라이브러리 버전을 구버전으로 사용하시는 이유가 있으신가요?

**Comment by XOneto9** [comment]
@heyman333 
아, 특별하진 않구요. 처음엔 최신 버전 지금 보면 1.21.1이 최신 같아요. 이걸로 했었는데, 에러가 나서 다시 그냥 혹시나 하는 마음에 Readme.md에 작성하신 내용중에 KakaOpenSDK를 1.20.0으로 하셨길래 혹시나 호환문제가 있나 싶어서 해봤습니다.

**Comment by venzersiz** [comment]
저도 동일한 문제가 있었는데요. RNKakaoLogins.xcodeproj가 아닌 RNKakaoLogins.xcworkspace를 추가하니 빌드 정상적으로 되었습니다.

**Comment by XOneto9** [comment]
@venzersiz 
감사합니다.
그런데 궁금한 점이 RNKakaoLogins.xcworkspace를 어디서 얻은 건가요?
저는 yarn을 통해서 설치된 node_module 안에 react-native-kakao-login 안에서 iOS 폴더 안에 있는 루트에서 얻은건데, 그렇다면 이 설치된 node_module안에 iOS 폴더에서 pod install로 얻으신건가요??

**Comment by venzersiz** [comment]
@XOneto9 아 죄송하니다; 제가 잘못보고 잘못했었네요. 지금 저도 같은 이슈로 헤딩하고 있어서요. 문제 해결이 되면 공유드리겠습니다.

**Comment by venzersiz** [comment]
@XOneto9 전 그냥 https://github.com/JeffGuKang/react-native-kakao-login 이거 쓰려고 합니다. 오토링킹 바로 적용되서 매우 편하게 되네요.

이 라이브러리를 쓰면, 매번 다른 에러가 나서 포기하려고요. (제가 iOS를 거의 모릅니다.) 나중에 다시 한 번 도전해보렵니다.

다 지우고 새롭게 설치해서 했는데,  :-1: Undefined symbol: ___isPlatformVersionAtLeast 에러가 납니다.
찾아보니 카카오 버전 이슈 같기도 한데, 이 라이브러리는 특정 버전으로 고정되어 있는 거 같아서요.
참고: https://devtalk.kakao.com/t/sdk-xcode-10/91678

**Comment by XOneto9** [comment]
@venzersiz 
아하, 한 번 저도 적용해 볼게요 뭐 이거 저거 다 해봐야 하는 상황이라서요'
감사합니다. ㅎㅎ

**Comment by heyman333** [comment]
@venzersiz  @XOneto9먼저 현재 버전이 2.4.1까지 올라가 있으니 최신버전으로 설치를 시도하신다면 autolink로 설치가 잘 되라라 생각합니다..(RN0.60이상 버전을 쓰고 있다고 가정) 1점대에 많은 설치 관련 오류가 있어서 계속 수정하면서 버전업을 했었거든요 ㅎㅎ

**Comment by deenMuhammad** [comment]
Why this issue is closed, It is not solved yet.
I have not seen any closed issue being solved here! All the closed issues do not have any answer.
The maintainers seem little careless.

**Comment by jungsunwoung** [comment]
저도 이 에러가 뜨는데 혹시 해결하셨나요?실제 파일을 경로에 넣어주고 다 해봤는데 안되네요ㅠㅠ

**Comment by XOneto9** [comment]
@jungsunwoung 
react native 인가요 expo 인가요?
그리고 어떤현상이 나타나고 있나요?
이거 제가 예전에 남긴 글이라 현재는 문제가 없는듯한데 
어떻게 어느 환경에서 문제가 되고 있나요?

**Comment by heyman333** [comment]
@jungsunwoung @deenMuhammad 
이슈를 다시 오픈 하곘습니다!
자세한 개발환경을 이슈템플릿과 함께 새로 만들어주시면 더 감사하곘습니다

**Comment by XOneto9** [comment]
@heyman333 

안녕하세요 수고가 많으시네요.
다름이 아니라. readme.md 파일을 조금 자세히?! 작성하시면 어떨까합니다..

얼마전에도 같은 문제로 저에게 따로 메일을 보내주신 분도 계셨는데,
저도 저 에러가 떴던 부분은,

보통 expo를 쓰더라고, ios에서 auto link가 되어 사실 딱히 문제가 되지 않습니다.

그런데 많은 분들이 저 auto link로 pod install 뿐만 아니라 react-native 0.62 이하 버전에서 하듯, 혹은 메뉴얼리 하게 설치하듯,
RNKakaoLogins.xcodeproj를 추가로 추가하는 부분에서 에러가 생기는 듯합니다..

사실 요즘은 0.62(아마 대부분일 것 같습니다만...) 가 거의 다일 것 같은데요. 이부분이 명확히 나뉘어 지지 않아서,
cocoapods으로 설치되는 것에 RNKakaoLogins.xcodeproj도 적용하여서 중복?! 적용을 시키는 듯합니다..

그래서 이 문제는 그냥... readme를 조금 명료하게 수정하면 어떨까요???

**Comment by heyman333** [comment]
@venzersiz 아 네 의견감사합니다! 엑스포를 쓰시는 분들이 매뉴얼로 추가를 또 해서 문제가 생기는거같네요 내용추가 할게요!

**Comment by heyman333** [comment]
@venzersiz 다시 생각해보니 저도 그 문제를 인지해서 "특별한 경우가 아니라면 필요하지 않습니다" 등 중복 셋팅을 막는 문구를 추가 했었네요.
다만 expo사용시에 설치법이 명확하지가 않은거같은데 혹시 expo에서 저희 모듈을 사용해 보셨나요?
expo는 따로 pod install등을 따로 해주지 않는것 같은데, 그렇다면 저희 모듈도 pod install이 자동으로 되는건가요?
혹시 expo를 써보셨다면 답변 부탁드리겠습니다~

**Comment by XOneto9** [comment]
@heyman333 
음..이거 혹시 코멘트 저에게 남기신건가요?? 아닌가...흐름은 저같은데...코멘트를 다른분께 남긴것 같아서...모르겠지만..
그냥 답변을 드릴게요.....(저 아니라면 ㅈㅅ....)

현재 expo로 사용하고 있구요. 앱도 배포 중에 있구요..
일단 epxo를 아시겠지만 설명을 간략히 드리면..

expo는 일종에 react-native 툴이라고 보면 될것같아요.
그냥 일반적인 expo에선 본 모듈을 사용할 수 없습니다. 이유는 expo 그룹에서 추가하지 않는한 사용할수 없죠.

빠르게 리엑트를 올릴수 있는 장점은 있지만 모듈 제한이 걸립니다. 그래서
eject를 하는데 이렇게 되면 그냥 일반적인 react-native라고 보면 됩니다. 차이가 있다면 그냥 환경을 보다 쉽게 설정해 준다는정도???
expo sdk도 쓸수 있으면서 외부 모듈을 쓸수 있는거거든요..

그래서 pod install을 expo eject를 할 경우엔 필히 해줘야 합니다.
(이건 react-native와 같기때문에, 실제 빌드를 해도 해당 환경인, 안드로이드 스튜디오와, xcode에서 각각 빌드를 해야합니다.
순수 expo의 경우 expo 자체가 그냥 빌드를 해주기 때문에 상관없습니다.)

결국 expo를 eject했느냐 안했느냐 차이로 나뉩니다.. 도움이 되셨는지요...

**Comment by heyman333** [comment]
@XOneto9 아 네 감사합니다 결국에 expo를 사용한다면 저희 카카오 로그인 모듈을 사용하지 못하고 eject를 해야 되군요,답변 감사합니다!

**Comment by XOneto9** [comment]
@heyman333 딱히 더 문제가 없다면 이 이슈는 닫아도 될것  같습니다.

**Comment by JD-YANG** [comment]
이 문제를 겪고있는데요, 혹시 RNKakaoLogins.xcworkspace 를 어떻게 찾을 수 있는지 문의드립니다. 저같은경우는 Header Search Path 로 강제로 지정했더니 이번엔 RNKKakaoLogins 를 빌드할 시에 KakaoOpenSDK/KakaoOpenSDK.h 를 못찾는다고 뜨고있네요....빌드 과정 자체가 이해하지 못하고있는데요, 먼저 RNKKakkaoLogin 을 빌드하고, 빌드된 라이브러리를 XCode 에서 링크하는게 맞는지요, 저같은경우는 expo 와 그냥 native build 를 둘다 쓰고 있습니다. 둘 중 하나라도 되면 될텐데, 낌새가 보이지않네요 ㅠ

**Comment by JD-YANG** [comment]
그리고 혹시 현재 Example Project 는 빌드가 되는 것인게 맞는지요, 참고하려고 확인하였으나 역시 빌드 실패가 떠서.. 제가 뭔가 놓친게 있나 싶어서요.

**Comment by heyman333** [comment]
@JD-YANG 네 https://github.com/react-native-seoul/react-native-kakao-login#how-to-run-example-project 를 참고하시고 예제프로젝트를 돌려보시면 될것 같습니다

**Comment by jungsunwoung** [comment]
헐 죄송합니다 제가 질문해놓고 며칠간 다른작업을 하느라 확인을 못했네요
저는 react-native로 작업중이고 안드로이드로 카카오로그인 빌드에는 성공했는데 위에 말씀하신 React/RCTBridgeModule.h"file not found문제로 아직 해결을 못했었는데 혹시몰라 manual install부분을 넘어가고 해보니 위의 문제는 해결된 것 같습니다. 늦은 코멘트 죄송합니다ㅠ
