### ISSUE TITLE
로그인 페이지가 뜨지 않습니다. `null is not an object`

### ISSUE THREAD

**Issue by XOneto9** [react-native-seoul/react-native-kakao-login#108]
카카오 오그인 라이브러리: 1.21.1 (이 번에는, 수동으로 framework에 넣었습니다. 그러나 pods를 사용하여 설치해도 마찬가지의 오류가 나타납니다.)
리엑트네이티브: sdk-36.0.1
expo 사용: 36.0.0
expo-kit : 36.0.1
platform: iOS, android

```
TypeError: null is not an object (evaluating 'RNKakaoLogins.login')
```

이라는 에러가 발생합니다. 안드로이드에서도 문제인데요.
sample code로 작성하였습니다.
plist.info, url types도 설정해 주었습니다.

![IMG_3874](https://user-images.githubusercontent.com/18350072/76696989-cb695800-66d4-11ea-8f86-4ace2e4d9f97.png)
![IMG_3875](https://user-images.githubusercontent.com/18350072/76696992-d02e0c00-66d4-11ea-8f8d-0da2abd50551.png)

![스크린샷 2020-03-15 오후 3 50 10](https://user-images.githubusercontent.com/18350072/76697037-63674180-66d5-11ea-80de-cfe03ac9bf31.png)
![스크린샷 2020-03-15 오후 3 49 34](https://user-images.githubusercontent.com/18350072/76696991-cdcbb200-66d4-11ea-92b8-6ce59bbb7893.png)

**Comment by heyman333** [comment]
이슈리포트 감사합니다. expo로는 개발설정을 잘 안해봐서 설정에 관한 내용을 문서에서 잘 다루고 있지 않았습니다 😭
궁금한점이 있는데 expo sdk 36버전부터는 RN 0.61.4 버전이 호환이 되는데 굳이 예전 버전으로 설치하시는 이유가 있으세요?

**Comment by XOneto9** [comment]
@heyman333 
딱히 이유는 아니구요. 처음에 expo-cli를 설치할때 36 버전 이였는데요 eject해서 그냥 설치된 내용을 보니까..
sdk-36.0.1 버전이더군요.
혹시나 해서 yarn add react-native로 최신판을 설치했지만 마찬가지 오류가 나길래..

해당 프로젝트를 12시간째 지우고 설치하고 하고 있네요 ㅠ 이유를 몰라서...

**Comment by heyman333** [comment]
@XOneto9먼저 현재 버전이 2.4.1까지 올라가 있으니 최신버전으로 설치를 시도하신다면 autolink로 설치가 잘 되라라 생각합니다.. 1점대에 많은 설치 관련 오류가 있어서 계속 수정하면서 버전업을 했었거든요 ㅎㅎ
