### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by venzersiz** [react-native-seoul/react-native-kakao-login#109]
### Version of kakao-login libraries

2.4.1

### Version of react-native

0.61.1

### Platforms you faced the error (IOS or Android or both?)

iOS

### Expected behavior

Xocde에서 빌드 시 에러가 나지 않아야 함.

### Actual behavior

오토 링크 사용 중에 있으며,
Xcode에서 빌드 시 에러가 납니다.

가이드의 npm 설치, pod install 까지 한 뒤 Xcode에서 빌드했습니다.

기존에 설치하다 좀 헤매서, Post installation 부분은 따라한 상태입니다.

Undefined symbols for architecture arm64:
  "___isPlatformVersionAtLeast", referenced from:
      ___33-[KLKTalkLinkCenter _callLinkAPI]_block_invoke_2 in KakaoLink(KLKTalkLinkCenter.o)
      -[KNVNaviLauncher initWithConfiguration:] in KakaoNavi(KNVNaviLauncher.o)
      -[KOTalkAuthorizeTask startWithCompletion:] in KakaoOpenSDK(KOAuthorizeTask.o)
      -[KOStoryAuthorizeTask startWithCompletion:] in KakaoOpenSDK(KOAuthorizeTask.o)
      -[KOSession initWithAppKey:redirectUri:] in KakaoOpenSDK(KOSession.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Tested environment (Emulator? Real Device?)

iPhone XR, Generic iOS Device 둘 다 동일하게 발생합니다.

**Comment by heyman333** [comment]
기존에도 비슷한문제가 있었는데 혹시 expo를 사용하시다가 detatch 하셨다면 참고 바랍니다~
https://github.com/react-native-seoul/react-native-kakao-login/issues/33

**Comment by venzersiz** [comment]
@heyman333 expo를 한 번도 사용하지 않았습니다. 일단 링크 참고해서 다른 시도를 해보겠습니다.

**Comment by heyman333** [comment]
@venzersiz 네 감사합니다! 혹시 최근에 모듈 업데이트 하다가 문제가 생겼을 수도 있겠네요 . 저도 시간내서 한번 더 설치과정에 문제가 있는지 확인해보겠씁니다.

기존 설치 과정중에 꼬였을 수도 있으니, 한번 더미 프로젝트를 만들어서 매뉴얼을 차근히 읽어보시고 다시 설치 해보시는것도 추천 드립니다~

**Comment by venzersiz** [comment]
@heyman333 문제 해결하였습니다.

제가 iOS에 대해서 모르다 보니까 이게 올바른 해결법인지는 모르겠습니다.

에러 메시지를 보면 KakaoLink쪽 이슈인 것으로 추측되어, 구글링을 해보니 이곳(https://devtalk.kakao.com/t/sdk-xcode-10/91678)에서 KakaoOpenSDK 1.20.0의 문제가 아닌가 싶었습니다. 이전에 다른 Issue에서 이 라이브러리가 최신 버전을 사용한다고 말씀하셨는데, node_modules/@react-native-seoul/kakao-login/kakao-login.podspec을 보니 s.dependency 'KakaoOpenSDK', '~> 1.20.0'로 되어 있었고, 그 부분을 s.dependency 'KakaoOpenSDK', '~> 1.21.0'으로 변경하고 빌드하니 정상적으로 빌드가 되었습니다.

다시 말씀드리지만, 제가 잘 모르기 때문에 이게 해결법인지는 모르겠습니다. 혹시 이게 근본 원인이 된다면, 이 라이브러리에 대해서 수정 요청드리겠습니다.

감사합니다.

**Comment by heyman333** [comment]
@venzersiz 친절한 설명 감사드립니다. 참고해서 다음 업데이트때 반영하겠습니다 감사합니다
