### ISSUE TITLE
Native module RNKakaoLogins tried to override RNkakaoLoginsModule

### ISSUE THREAD

**Issue by ollabu3** [react-native-seoul/react-native-kakao-login#110]
### Version of kakao-login libraries

1.28.0
### Version of react-native

0.61
### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior

react-native run-build
### Actual behavior

4. 안드로이드 카카오 SDK 설치 후의 설정과 관련해서는 카카오 개발자 페이지 - 앱생성을 참고해주세요. 앱생성 가이드를 따라하고 성공적으로 build가 되는 것을 확인하시면 아래를 진행하시면 됩니다. 

이때까지는 build가 되었는 데 5. 후 build를 하면 에러가 납니다.
![Screenshot_1584693636](https://user-images.githubusercontent.com/53179876/77148227-78c3dd80-6ad2-11ea-8cad-a8ee0a684d1d.png)

### Tested environment (Emulator? Real Device?)

emulator 9.0

**Comment by heyman333** [comment]
https://github.com/react-native-seoul/react-native-kakao-login#manual-installation 이부분 작업으을 해주신거 같은데 RN 0.60이상부터는 자동으로 link가 되므로, 작업을 안해주셔도 됩니다!

**Comment by heyman333** [comment]
여기도 참고 해주세요~
https://github.com/react-native-seoul/react-native-kakao-login/issues/100

**Comment by ollabu3** [comment]
> 여기도 참고 해주세요~
> #100
> 
> 그런데 왜 버전을 구버전을 사용하시나요?????? 되도록이면 최신버전 설치를 부탁드립니다
> `"@react-native-seoul/kakao-login": "^2.4.1",`

친절하고 빠른 답변 감사합니다! 현재 2.4.1버전으로 설치되어 있습니다. 

답변하신 것처럼 진행하였으나 에러가 계속 납니다ㅜ 혹시 gradle 5.0버전 이상에서 지원이 되나요?

**Comment by heyman333** [comment]
> > 여기도 참고 해주세요~
> > #100
> > 그런데 왜 버전을 구버전을 사용하시나요?????? 되도록이면 최신버전 설치를 부탁드립니다
> > `"@react-native-seoul/kakao-login": "^2.4.1",`
> 
> 친절하고 빠른 답변 감사합니다! 현재 2.4.1버전으로 설치되어 있습니다.
> 
> 답변하신 것처럼 진행하였으나 에러가 계속 납니다ㅜ 혹시 gradle 5.0버전 이상에서 지원이 되나요?

이부분은 원래 저게 들어가 있었는데 뺴셨다는거죠? import 구문도 빼주시고 
모두 뺴셨다면  android 폴더에서 `./gradlew clean`를 진행해주시고, 
혹시 모르니 `react-native start --reset-cache`까지 실행 해주시기 바랍니다 ~😀

**Comment by ollabu3** [comment]
네 Manual installation에 있는 1~3번까지 다 빼고 했습니다! 
```./gradlew clean```시 ```Task 'clean' not found in root project '프로젝트이름'.```가 뜨는데 이것이 문제일까요?

**Comment by heyman333** [comment]
@ollabu3 음 그게 문제는 아닌거같은데,,, 다시 빌드를 해보셔도 위와 같은 메세지가 보인다면 아직 코드삭제가 제대로 되지 않은 걸 수도 있습니다. 빌드 환경은 osx를 사용하시나요?

**Comment by ollabu3** [comment]
> @ollabu3 음 그게 문제는 아닌거같은데,,, 다시 빌드를 해보셔도 위와 같은 메세지가 보인다면 아직 코드삭제가 제대로 되지 않은 걸 수도 있습니다. 빌드 환경은 osx를 사용하시나요?
> 정확히 라이브러리가 동작하는지 확인해보려면 더미프로젝트를 만들어서 다시 설치 해보시는것도 추천드립니다

빌드환경은 Linux입니다 말씀하신대로 더미프로젝트 수행 후 답변드리겠습니다ㅎㅎㅎ 감사합니다!

**Comment by ollabu3** [comment]
build 정상적으로 처리됩니다. 혹시 로그인했을 때 이 창으로 넘어가는것이 정상인가요?
![Screenshot_1584757813](https://user-images.githubusercontent.com/53179876/77217660-6e9fee80-6b67-11ea-81ad-eff7168a6962.png)

**Comment by heyman333** [comment]
@ollabu3 네 맞습니다

**Comment by ollabu3** [comment]
네 감사합니다 주말에도 빠른답변 감사합니다. 좋은하루 보내세요!

**Comment by ringle-admin** [comment]
안녕하세요! 안드로이드에서 llegalStateException: Session is not initialized. Call KakaoSDK#init first.에러가나서, 메뉴얼 installation을 시도 했는데요, 이 경우 위의 이슈가 발생합니다. 어떻게 접근하면 될까요? 감사합니다!
