### ISSUE TITLE
다른 카카오계정으로 로그인 시 에러

### ISSUE THREAD

**Issue by ollabu3** [react-native-seoul/react-native-kakao-login#113]
### Version of kakao-login libraries

2.4.1
### Platforms you faced the error (IOS or Android or both?)
0.61

### Expected behavior
로그인 버튼 -> 다른 카카오계정으로 로그인 -> 로그인 시 에러가 납니다.

### Actual behavior
정상적으로 인증이 되어야 함

### Tested environment (Emulator? Real Device?)

![20200325_140820](https://user-images.githubusercontent.com/53179876/77503959-5c44ee00-6ea2-11ea-8e5a-2c1828f57a7b.jpg)

간편로그인은 잘 처리되지만 다른 계정으로 로그인을 누를 시 이러한 에러가 나는데 따로 설정해야 하는것이 있나요?

android 10 version

**Comment by ollabu3** [comment]
그리고 하나더 물어보겠습니다. 제가 생각했을 때  react-native-seoul/kakao-signin 라이브러리는 개발자가 accessToken과 같은 것들을 redirect url 필요없이 react-native-seoul/kakao-signin 라이브러리를 통해 쉽게 서버에서 별도의 처리없이 인증절차를 생략하여 받을 수 있는거라고 이해했는데 그것이 맞는지요..

**Comment by heyman333** [comment]
@ollabu3 제 생각이지만 인증이라고 말씀하는 부분이 이사람이 정말 카톡유저가 맞는지만 결정한다면 별도의 서버 로직은 필요 없을거같고, 본인인증등 추가적인 인증이 있어야 한다며 별도의 서버 로직이 있어야 하지 않을까요

서버를 두고 있는 서비스의 경우라면 보통 카카오톡은 회원가입시 유저관리의 용도(kakakoid를 id값으로)로 사용하고 자체서버 토큰을 발급하는식으로 하는 것으로 알고 있씁니다.

저 위에 버그는 저도 좀 찾아야겠네요 ㅎㅎ 에러메시지만 봐서는 뭔가 클라이언트 id가 등록이 안됐다는거같은데 ..
저도 사실 다른 아이디로 로그인은 한번도 안해봤네요ㅠㅠ
iOS는 정상적으로 잘 되나요?

**Comment by ollabu3** [comment]
android를 목적으로 개발을 하는거라서 IOS로는 확인을 못하고 있습니다.
 @heyman333 님께서 말씀하신 것처럼 본인인증등 추가적인 인증이 있어야 하면 client에서 acessToken을 서버에 보내고 서버에서 kakao 로그인 Redirect URI을 이용해서 정보를 보내고 처리해야 한다는 말씀인가요? 제가 필요한 정보는 user의 name, age, email정도여서  KakaoLogins.getProfile()을 통해 client에서 정보를 받고 그걸 server로 넘겨주려고 했습니다.

**Comment by heyman333** [comment]
@ollabu3 네 저도 안드로이드에서 테스트 해봐야겠네요...ㅠ 네 서버자체적으로 outh를 구현하는 식으로 하구요(ex : jwt) 어쩃든 서버 api에 접속하려면 토큰은 새로 발급 하셔야 하자나요?

**Comment by ollabu3** [comment]
네 빠른답변 항상 감사합니다ㅎㅎㅎ!
