### ISSUE TITLE
회원이 탈퇴하는 경우 연결 끊기 API를 호출은 어떻게 하나요?

### ISSUE THREAD

**Issue by ddimsoft** [react-native-seoul/react-native-kakao-login#114]
### Version of kakao-login libraries

2.4.1
### Version of react-native

RN 0.61

### Platforms you faced the error (IOS or Android or both?)

Android/IOS

### Expected behavior

회원 탈퇴시 처리해야 하는 
연결 끊기 작업 
### Actual behavior

Kakao Developers 개발 문서에 의하면, 사용자가 탈퇴하는 경우 연결 끊기 API를 호출하도록 되어 있는데 
어떻게 해야 하는 건가요?

**Comment by heyman333** [comment]
@ddimsoft  해당 기능은 아직 구현이 되지 않았습니다. ㅠㅠ

**Comment by heyman333** [comment]
@ddimsoft 다음 업데이트 때 로그아웃 / 연결끊기 기능을 추가해야겠네요...ㅠ

**Comment by ddimsoft** [comment]
부탁드립니다. ^^*
