### ISSUE TITLE
간헐적으로 첫 로그인 요청 시점에 아무런 반응이 없는 경우가 발생합니다.

### ISSUE THREAD

**Issue by jaeYoung-k** [react-native-seoul/react-native-kakao-login#115]
### Version of kakao-login libraries 
 v2.4.1
### Version of react-native 
0.61.5
### Platforms you faced the error 
Android
### Expected behavior
로그인 요청시 로그인이 되어야 합니다.

### Actual behavior
간헐적으로 첫 로그인 시점에 아무 반응이 없는 경우가 발생합니다.
로그를 찍어 봤을 때  "App restarted during Kakao login procedure. Restarting from the start." 이렇게 메세지가 내려옵니다.

### Tested environment 
Real Device (Galaxy s10) 환경입니다.

감사합니다.

**Comment by pyeonjaesik** [comment]
저는 IOS에서   "카카오톡으로 간편로그인"을 클릭하면 아무런 반응이 없습니다. 에러도 뜨지 않구요...
"다른 카카오계정으로 로그인"을 클릭하였을 때는 잘 작동합니다.

**Comment by JeffGuKang** [comment]
@pyeonjaesik 
1. 로그인 시도시 카카오톡이 설치되어 있는 상태셨나요? 
아니면 아이디 비번을 입력하여 시도하셨나요? 

2. 카카오톡이 설치되어 있는 상태라면, 카카오톡을 완전종료한 상태에서 로그인과 카카오톡이 실행중일때 로그인 동작이 정상적으로 되나요?

**Comment by reiui9** [comment]
저도 ios에서 간편 로그인으로 접속 할 경우 아무런 반응이 없습니다.

**Comment by floydkim** [comment]
저희 앱에서도 발생하고있어서 사례 추가합니다


### Version of kakao-login libraries
v2.10.0

### Version of react-native
v0.63.2

### Platforms you faced the error
갤럭시 S10(Android 10), S9(Android 9) 모두 발생

---

인증수단 선택 다이얼로그에서 **'카카오톡으로 간편로그인' 버튼을 누를 때** 발생하고, catch 블락에서 console찍으면 `App restarted during Kakao login procedure. Restarting from the start` 메시지가 확인됨
 -> 이 때 await 구문에서 벗어나므로 로그인 모듈의 결과값을 받을 수 없음.

특이사항
- 카카오톡 - **설치는 되어있으나 로그인 되어있지 않은 상태**
  - 로그인한 후 안드로이드 설정에서 앱 데이터를 지웠거나
  - 권한 허용하고 로그인하지 않았거나
  - 권한 허용하고 카카오계정 로그인은 했으나 번호인증은 하지 않은 상태

따라서, 로그인은 카카오톡 앱이 아닌, 카카오SDK에서 띄운 웹뷰를 통해 이메일/비밀번호 입력해 로그인이 이뤄짐

참고사항
- 앱을 켠 후 최초 1회 항상 발생하고, 두번째엔 발생하지 않아 로그인에 성공함
- 카카오톡이 설치되지 않아 '다른 카카오계정으로 로그인' 시도할땐 발생하지 않음

**Comment by JeffGuKang** [comment]
현재 iOS의 다른 앱들도 카카오톡을 완전 종료한 상태로 로그인을 하면 한번은 무시되는 현상이 있는 듯 합니다. 카카오 SDK 문제로 보여집니다.

**Comment by yoojeen126** [comment]
저도 안드로이드에서는 비슷한 현상있는것으로 보입니다.
현재 테스트기기는 카카오톡이 없는 상태에서 테스트 했어요.
1.처음 로그인 시 카카오톡 웹화면이 나옵니다.
2.여기서 로그인 시도 시 결과값을 못받는것 같습니다.
3.재 로그인 시(미리 저장된 카카오톡계정) 정상적으로 로그인 되는걸 확인했습니다.

IOS 시뮬레이터에서는 이와 같은 방식으로 정상적으로 되는걸 확인했습니다.

**Comment by ShimTeacher** [comment]
갤럭시 노트 10+ 에서도 동일한 현상입니다.

**Comment by hyochan** [comment]
`3.0.1` 이후 버전을 사용하시고 문제가 생기시면 알려주시기 바랍니다 :pray:
