### ISSUE TITLE
SDK 2.0 적용 부탁드립니다.

### ISSUE THREAD

**Issue by infinitytn** [react-native-seoul/react-native-kakao-login#120]
### Version of kakao-login libraries

2.0.0-beta.3
https://developers.kakao.com/docs/latest/ko/getting-started/sdk-ios

### Version of react-native

rn cli 로 시작한 0.62.2 버전입니다

### Platforms you faced the error (IOS or Android or both?)

both

### Tested environment (Emulator? Real Device?)

에뮬레이터, 리얼(iphone 6s)

### 요청사항

kakao sdk 2.0 적용을 부탁드립니다.

**Comment by heyman333** [comment]
네 확인해보고 적용해보겠습니다. 직접 적용해보시고 pr을 보내셔도 좋습니다^^

**Comment by sunkibaek** [comment]
@heyman333 안녕하세요~ ㅎㅎ

혹시 로드맵이나 향후 개발 계획 같은 걸 정리해 두신 게 있으신가요? 공유해주시면 저도 시간 되는대로 돕고 싶습니다~~

**Comment by heyman333** [comment]
@sunkibaek 안녕하세요 선기님! 로드맵은 따로 정리 한게 없어요..ㅠ 구체적으로 계획한 내용은 없으니 로드맵을 정리해서 pr을 보내주셔도 좋고, 직접 기능 구현을 해서 주셔도 감사할 거 같습니다👍👍👍👍👍

**Comment by sunkibaek** [comment]
@heyman333 넵, 프로젝트 관리하시느라 고생 많으십니다~! 이슈에는 문제가 되는 부분들만 올라오지만 훨씬 더 많은 분들이 감사하게 사용하고 계실거에요~!

**Comment by JeffGuKang** [comment]
v2 정식 출시되었습니다. 

https://devtalk.kakao.com/t/kakao-sdk-android-ios-2-0-0-notice-the-new-version-of-sdks-for-ios-android-released/107820

**Comment by heyman333** [comment]
@JeffGuKang 허윽...기존 버전 없애기전에 언능 업데이트 해야겠네요..ㅠ

**Comment by JeffGuKang** [comment]
@heyman333 저도 기존 카카오 로그인 마무리하고 여기 기여해야겠어요. 마무리를 못하고 있네요 ㅡ,.ㅜ

**Comment by Wanderlust-sol** [comment]
2.0 맞게 현재 적용되어 있는 건가요?

**Comment by heyman333** [comment]
@Wanderlust-sol 아뇨 아직 적용 안됐습니다 ㅠㅠ

**Comment by hyochan** [comment]
장기간 지원이되고 있지 않은듯 하여 제가 빠르게 `3.0.0`으로 적용 완료했습니다. #191
