### ISSUE TITLE
IOS >= 13 에서의  로그인 오류

### ISSUE THREAD

**Issue by pyeonjaesik** [react-native-seoul/react-native-kakao-login#122]
Iphone se  (IOS>13.3.1) 에서 "다른 아이디로 로그인"클릭시 문제 없지만
"카카오 아이디로 로그인"을 클릭하면 아무런 반응이 없습니다.

**Comment by pyeonjaesik** [comment]
IOS  12 이하에서는 문제 없습니다. 하지만 IOS 13 이상부터는 아무런 반응이 없습니다.

**Comment by mnkang89** [comment]
@heyman333 
ios13이상 버전에서 동일한 현상 발생하고 있습니다 ㅠ.ㅠ 
혹시 수정작업중에 있으실까요?

정말 잘쓰고 있습니다 감사합니다.

**Comment by heyman333** [comment]
@mnkang89 실제 기기에서 발생하는 문제인가요?
예제프로젝트에서 테스트 할때는 문제가 발생하지 않네요,,,(에뮬입니다)

환경설정등 다시 확인 해보시고 그래도 안되면 다시 말씀해주실수 있을까요???
<img width="408" alt="스크린샷 2020-06-20 오후 4 20 55" src="https://user-images.githubusercontent.com/22214150/85195995-0dc4b580-b312-11ea-8cf1-22f114c2fd31.png">

**Comment by mnkang89** [comment]
네 다시금 설정해보고 해보겠습니다.
친절한 답변 정말 감사드립니다!
​
-----Original Message-----

**Comment by reiui9** [comment]
저도 실제 기기에서 카카오 간편로그인이 작동하지 않습니다.

**Comment by reiui9** [comment]
혹시 간편로그인을 disable 시키는 방법은 있을까요

**Comment by JungDonggun** [comment]
@pyeonjaesik @reiui9

iPhone Xs MAX 기준

Podfile에 해당 라인을 추가하니 정상적으로 동작했습니다.

target 'yourApp' do
...
pod 'KakaoOpenSDK', '~> 1.21.0' # append this line
end

**Comment by KYEBOKWAK** [comment]
저도 동일증상이 나오고 있습니다.

카카오톡으로 간편로그인 터치시 아무런 콜백이 넘어오지 않고 있습니다.(catch도 안옴)

안드로이드에선 정상동작 하고 아이폰에서만 이슈가 있네요.

**Comment by KYEBOKWAK** [comment]
> @pyeonjaesik @reiui9
> 
> iPhone Xs MAX 기준
> 
> Podfile에 해당 라인을 추가하니 정상적으로 동작했습니다.
> 
> target 'yourApp' do
> ...
> pod 'KakaoOpenSDK', '~> 1.21.0' # append this line
> end

추가 되어 있는데도 증상이 있네요..

**Comment by KYEBOKWAK** [comment]
카카오톡이 설치되어 있지 않으면 

카카오계정 로그인으로 진입 하기때문에 정상동작 합니다. (애뮬)

설치되어 있는 상황이라면 

간편로그인이 뜨고, 터치시 카톡으로 전환되어 돌아올때 아무런 callback이 오지 않습니다.

**Comment by heyman333** [comment]
@KYEBOKWAK 정확히는 뭔지 모르겟지만 설치과정에서 kakao sdk 와 프로젝트간의 설정이 잘못된건 아닐까요

**Comment by heyman333** [comment]
추후에 크게 이슈레이징 되지 않이 해당 이슈는 클로즈하곘습니다 :D
