### ISSUE TITLE
카카오 버튼에 대한 옵션 주기

### ISSUE THREAD

**Issue by pyeonjaesik** [react-native-seoul/react-native-kakao-login#124]
카카오로그인 버튼 클릭했을 때 "카카오 아이디로 로그인" ,"카카오 스토리로 로그인", "다른아이디로 로그인" 버튼이 팝업되어 이중 하나를 골라 로그인하는 형식이었는데요. 이렇게 말고
"다른 아이디로 로그인"으로만 로그인 하는 방법은 없을까요?

**Comment by heyman333** [comment]
네 해당 옵션은 한번 찾아보겠습니다.
많은 분들이 보실 수 있는 레포이니 최소한 이슈템플릿을 지켜서 작성해주시면 감사하겠습니다:D

**Comment by heyman333** [comment]
참고: 
https://github.com/react-native-seoul/react-native-kakao-login/issues/115
