### ISSUE TITLE
연결끊기 API 지원

### ISSUE THREAD

**Issue by KimChungHun** [react-native-seoul/react-native-kakao-login#125]
### Version of kakao-login libraries

2.4.3

### Version of react-native

0.61.5

### Actual behavior

이것 저것 테스트를 하는 중에 연결끊기 API가 꼭 필요한 경우가 발생을 하고 있습니다.
연결끊기 API도 지원이 된다면 더 좋을 것 같아서 요청 드려봅니다.

Android
https://developers.kakao.com/docs/latest/ko/kakaologin/android#unlink

ios
https://developers.kakao.com/docs/latest/ko/kakaologin/ios#unlink

**Comment by heyman333** [comment]
네 다음 업데이트때 반영하겠습니다. 감사합니다!
