### ISSUE TITLE
 [ios]카카오톡으로 간편 로그인

### ISSUE THREAD

**Issue by liamstory** [react-native-seoul/react-native-kakao-login#13]
안녕하세요. 정말 좋은 api를 만들어주셔서 감사합니다.
그런데 동작중에 문제가 있는거 같아서 질문드립니다.
![kakaotalk_photo_2018-08-01-22-36-08](https://user-images.githubusercontent.com/20754969/43524884-5535556a-95db-11e8-8caf-25bd36075ada.png)

사진에서 다른 카카오톡계정으로 로그인 버튼을 통해서 계정과 비밀번호를 입력하면 token을 받아오는데,
카카오톡으로 간편로그인을 클릭하면 카카오톡으로 넘어갓다가 다시 앱으로 왔지만 token을 받아오지 않는거같습니다.
getprofile을 클릭하면 error로 뜨고 카카오톡으로 간편로그인 클릭하면 다시 카톡으로 넘어갓다가 앱으로 오기를 반복합니다. 시간 나실때 확인 부탁드립니다.

더위 조심 하세요! 감사합니다.

**Comment by dooboolab** [comment]
@liamstory 네 제가 카톡을 잘 하지 않아서 테스트 환경이 많이 좋지 않네요.. 시간이 나면 보겠지만 당분간 확인하기 힘들 것 같아요. 혹시 `contribute`를 한번 도전해보셔도 좋을 것 같습니다!

**Comment by Bang9** [comment]
@liamstory  
AppDelegate에 아래 코드를 추가하지 않으면 세션이 오픈되지 않는 증상이네요


```
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
                                       sourceApplication:(NSString *)sourceApplication
                                              annotation:(id)annotation {
    if ([KOSession isKakaoAccountLoginCallback:url]) {
        return [KOSession handleOpenURL:url];
    }

    return false;
}

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
                                                 options:(NSDictionary<NSString *,id> *)options {
    if ([KOSession isKakaoAccountLoginCallback:url]) {
        return [KOSession handleOpenURL:url];
    }

    return false;
}

- (void)applicationDidBecomeActive:(UIApplication *)application
{
    [KOSession handleDidBecomeActive];
}
```

**Comment by heyman333** [comment]
@liamstory 
위에 @Bang9 님 말씀대로 해보시고 안되면 다시 이슈 열어 주시기 바랍니다~ 감사합니다.
