### ISSUE TITLE
ios에서 다른 앱에서 카카오 로그인했을 때 제 앱으로 리다이렉트 되는 오류

### ISSUE THREAD

**Issue by pyeonjaesik** [react-native-seoul/react-native-kakao-login#132]
다른 앱에서 카카오 로그인하면 제가 만든앱으로 강제 리다이렉트 됩니다.

이런 오류는 왜그런거죠?

**Comment by heyman333** [comment]
짧게 생각해보면

https://developers.kakao.com/docs/latest/ko/getting-started/sdk-ios-v1#app-key
등 카카오 API를 설정하는데 있어서 문제가 있지 않나 싶네요
