### ISSUE TITLE
간편로그인으로 바로 진입하게 할 수는 없을까요?

### ISSUE THREAD

**Issue by wkddnjset** [react-native-seoul/react-native-kakao-login#133]
### Version of kakao-login libraries

"@react-native-seoul/kakao-login": "2.4.3",
"react": "16.11.0",
"react-native": "0.62.2",

### Platforms you faced the error (IOS or Android or both?)

Android 입니다.

### Expected behavior

![KakaoTalk_Photo_2020-06-02-16-49-19](https://user-images.githubusercontent.com/22087542/83494358-1c793300-a4f1-11ea-8c85-8a22d5819321.jpeg)

카카오톡으로 간편로그인
카카오 스토리 계정으로 로그인
다른 카카오 계정으로 로그인

이런식으로 팝업이 뜨는 형태인데,
바로 "간편로그인"으로 로그인 되는 형태로 개발이 가능할까요?

### Tested environment (Emulator? Real Device?)

갤럭시 A90 입니다.

**Comment by heyman333** [comment]
@wkddnjset sdk 공식 문서를 한번 봐야겠네요 혹시 그전에 방법을 찾으시면 피드백 부탁드립니다~

**Comment by nicholaskim94** [comment]
카카오 로그인 세션을 open할때 AuthType을 .talk로 넘겨주면 됩니다
https://developers.kakao.com/sdk/reference/ios-legacy/release/Constants/KOAuthType.html

```objc
[[KOSession sharedSession] openWithCompletionHandler:^(NSError *error) {
...
} authType:(KOAuthType)KOAuthTypeTalk, nil]];
```

@heyman333 `login` API에 AuthType을 optional 한 parameter로 추가 가능할까요?

**Comment by heyman333** [comment]
@nicholaskim94 네 감사합니다. 다음업데이트때 반영하곘습니다.
