### ISSUE TITLE
IOS 로그인 시도 시 앱 중지

### ISSUE THREAD

**Issue by kai-lykt** [react-native-seoul/react-native-kakao-login#136]
"@react-native-seoul/kakao-login": "^2.5.0",
"react-native": "0.62.2",
버전 사용중입니다.

iPhone 11 에뮬레이터에서 로그인 버튼 클릭 후 웹에서 로그인 성공 후 돌아올 때 앱이 종료되는 현상이 발생합니다.

아래는 오류 발생시 에러 로그입니다.

2020-06-19 15:29:39.204500+0900 Qsee[2696:117326] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[4]'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e3cf0e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50ba89b2 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23ecfa51 _CFThrowFormattedException + 194
	3   CoreFoundation                      0x00007fff23eda4a6 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:].cold.4 + 38
	4   CoreFoundation                      0x00007fff23e9b787 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 247
	5   CoreFoundation                      0x00007fff23e38e11 +[NSDictionary dictionaryWithObjects:forKeys:count:] + 49
	6   Qsee                                0x000000010a6e3113 __32-[RNKakaoLogins login:rejecter:]_block_invoke + 867
	7   Qsee                                0x000000010a75f0bb __27-[KOSession startAuthrize:]_block_invoke_3 + 217
	8   Qsee                                0x000000010a768ecd __56+[KOToken tokenTaskWithAuthCode:redirectUri:completion:]_block_invoke + 706
	9   Qsee                                0x000000010a1c8477 __79+[FLEXNetworkObserver asyncCompletionWrapperForRequestID:mechanism:completion:]_block_invoke + 1367
	10  CFNetwork                           0x00007fff22f5a4d0 CFNetwork + 38096
	11  CFNetwork                           0x00007fff22f6d740 _CFHTTPMessageSetResponseProxyURL + 17217
	12  Foundation                          0x00007fff2592128c __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	13  Foundation                          0x00007fff259211ad -[NSBlockOperation main] + 80
	14  Foundation                          0x00007fff259240dc __NSOPERATION_IS_INVOKING_MAIN__ + 17
	15  Foundation                          0x00007fff259203ee -[NSOperation start] + 731
	16  Foundation                          0x00007fff25924a20 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 17
	17  Foundation                          0x00007fff25924540 __NSOQSchedule_f + 182
	18  libdispatch.dylib                   0x000000010d2d74dc _dispatch_block_async_invoke2 + 83
	19  libdispatch.dylib                   0x000000010d2c8e8e _dispatch_client_callout + 8
	20  libdispatch.dylib                   0x000000010d2d6d97 _dispatch_main_queue_callback_4CF + 1149
	21  CoreFoundation                      0x00007fff23da0909 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	22  CoreFoundation                      0x00007fff23d9b459 __CFRunLoopRun + 2041
	23  CoreFoundation                      0x00007fff23d9a944 CFRunLoopRunSpecific + 404
	24  GraphicsServices                    0x00007fff38ba6c1a GSEventRunModal + 139
	25  UIKitCore                           0x00007fff48c8b9ec UIApplicationMain + 1605
	26  Qsee                                0x0000000109d56210 main + 112
	27  libdyld.dylib                       0x00007fff51a231fd start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by JungDonggun** [comment]
iPhone XS Max 디바이스에서도 같은 이슈가 발생합니다.

**Comment by JungDonggun** [comment]
Podfile에 해당 라인을 추가하니 정상적으로 동작했습니다.

target 'yourApp' do
    ...
    pod 'KakaoOpenSDK', '~> 1.21.0' # append this line
end

**Comment by Eumhongin** [comment]
혹시 어디부분에 추가하셨나요?
<img width="1031" alt="스크린샷 2020-07-06 오후 1 42 15" src="https://user-images.githubusercontent.com/23710025/86556515-82445900-bf8e-11ea-976d-09691e7f7661.png">

**Comment by JungDonggun** [comment]
@Eumhongin 네 맞습니다
