### ISSUE TITLE
RN 안드로이드 debug.keystore 키해시값 추출

### ISSUE THREAD

**Issue by huurray** [react-native-seoul/react-native-kakao-login#139]
### Version of kakao-login libraries

2.5.0

### Version of react-native

0.62.2

### Platforms you faced the error (IOS or Android or both?)

안드로이드

### Expected behavior

로그인이 정상작동 해야함

### Actual behavior

Login Failed:E_AUTHORIZATION_FAILED invalid android_key_hash or ios_bundle_id or web_site_url
로그인시 위에러가 발생하였습니다.

해결을 위해 사용한 방법
1. keytool -exportcert -alias androiddebugkey -keystore ~/.android/debug.keystore -storepass android -keypass android | openssl sha1 -binary | openssl base64
명령어를 사용해서 나온값을 카카오 개발자 콘솔에 등록하였는데 같은 에러 메세지를 받았습니다.

2. keytool -exportcert -alias androiddebugkey -keystore {프로젝트 경로}/android/app/debug.keystore -storepass android -keypass android | openssl sha1 -binary | openssl base64
키스토어 경로를 바꾸어 카카오 개발자 콘솔에 등록하였는데 같은 에러 메세지를 받았습니다.

3. 깃 문서에 
"React Native 0.60.x 부터 기본적으로 포함되는 디버깅 키의 해시는 다음과 같고 ../project/android/app에 디버그용 키스토어가 존재합니다"
ex: Xo8WBi6jzSxKDVR4drqm84yr9iU=
라고 문서에 적혀있어 ex 키해시값을 카카오 개발자 콘솔에 등록하였는데 **정상작동하였습니다.**

-----  

**문의드리는 내용은 debug.keystore로 부터 ex 키해시값을 어떻게 뽑았는지 알 수 있을까요??
앞으로 릴리즈 키스토어를 생성하고 거기서 키해시를 뽑을때 사용하기위해 그 방법을 질문드립니다.** 

안드로이드 해시키 관련 내용을 잘 몰라 헤매는 것같습니다.. 알려주시면 감사하겠습니다!!
(Mac 사용중)

### Tested environment (Emulator? Real Device?)

에뮬레이터

**Comment by huurray** [comment]
문서에 적혀있는 디버그 키를 카카오 개발자 콘솔에 등록하니 잘 되는 것을 확인했습니다.

- React Native 0.60.x 부터 기본적으로 포함되는 디버깅 키의 해시는 다음과 같고 ../project/android/app에 디버그용 키스토어가 존재합니다
ex: Xo8WBi6jzSxKDVR4drqm84yr9iU=

앞으로 앱을 배포할때는 keystore에서 키해시를 어떻게 추출하면 되나요?

**Comment by heyman333** [comment]
> 이 것도 해보고 카카오 개발자 콘솔에 등록하였는데 같은 에러 메세지를 받았습니다.

어떤에러를 받았는지 적어주시면 감사하겠습니다.
실질적으로 안드로이드 디버그 빌드를 할때 어떤 디버그 키스토어로 빌드가 되는지 gradle 설정을 해보시고 그에 해당하는 키스토어 해쉬값을 등록하셔야 합니다

**Comment by huurray** [comment]
@heyman333 
카카오 로그인 화면에서 아이디와 비밀번호를 치고 확인을 눌렀을때 
'Login Failed:E_AUTHORIZATION_FAILED invalid android_key_hash or ios_bundle_id or web_site_url'
이 에러 메세지를 받았습니다.

**Comment by heyman333** [comment]
@huurray ~/.android/debug.keystore -storepass android -keypass android | openssl sha1 -binary | openssl base64 
여기서 해쉬를 가져오시면 안되구요, 지금확인해보니까 `0.62.2` 버전부터는 
```gradle
signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
```
위에서 보시다시피 프로젝트 안에 있는 debug key로 빌드를 하네요
.
프로젝트 내에 `android/app/debug.keystore`의 해쉬를 가져오셔야합니다~

**Comment by jwoo9928** [comment]
keytool -exportcert -alias androiddebugkey -keystore .\프로젝트명\android\app\debug.keystore -storepass android -keypass android | openssl sha1 -binary | openssl base64
으로 해시키를 받아서 등록해도 
'Login Failed:E_AUTHORIZATION_FAILED invalid android_key_hash or ios_bundle_id or web_site_url'
가 발생합니다... 어떻게 해야할지 전혀 모르겠습니다 ㅠ

**Comment by hyochan** [comment]
@jwoo9928 프로젝트 내에서 모듈을 새로 설치하신 후 android studio 에서 invalidate caches and restart 를 해보시고 `rebuild`하시는 것을 추천 드립니다. 네이티브 코딩을 하시면 캐싱 문제가 많이 발생하는데 염두에 두시고 개발하시면 좋습니다.
