### ISSUE TITLE
E_UNKOWN Attempt to invoke virtual method 'java.lang.String com.kakao.usermgmt.response.model.Profile.getNickname()' on a null object reference 에러가 발생합니다.

### ISSUE THREAD

**Issue by peacel** [react-native-seoul/react-native-kakao-login#140]
### Version of kakao-login libraries

2.5.0

### Version of react-native

0.62.2

### Platforms you faced the error (IOS or Android or both?)

android

### Expected behavior

샘플코드의 getProfile()에서 KakaoLogins.getProfile()이 에러가 없이 정상적으로 결과를 가져와야 하는 부분입니다.

### Actual behavior

KakaoLogins.getProfile() 호출시 아래와 같은 에러가 발생합니다.

Get Profile Failed:E_UNKOWN Attempt to invoke virtual method 'java.lang.String com.kakao.usermgmt.response.model.Profile.getNickname()' on a null object reference

### Tested environment (Emulator? Real Device?)

갤럭시 노트 5

------------

https://github.com/react-native-seoul/react-native-kakao-login

이 곳에 있는 샘플 코드를 실행하였습니다.

카카오톡 로그인 > 필수만 동의 (가장 위에 것) > 그 후 토큰은 정상적으로 가져오고, GetProfile()을 호출하여 "Get Profile Start" 로그가 나온 후에 위에 적은 내용과 같이 "Get Profile Failed:..." 로그가 나타납니다.

**Comment by heyman333** [comment]
혹시 이렇게 됐을경우 앱이 죽나요? 아니면 그냥 단순히 경고 메세지는 아닌가요?
지금 확인해 보니 다음처럼 필수 항목이 아닌경우는 null로 데이터가 들어오는 것 같네요. (샘플프로젝트에서 확인)
![Screenshot_1593933066](https://user-images.githubusercontent.com/22214150/86527520-78f9b480-beda-11ea-852c-c5ccf031679f.png)
![Screenshot_1593933085](https://user-images.githubusercontent.com/22214150/86527535-a9415300-beda-11ea-8d94-ea1eec620a1b.png)

**Comment by LeeKyungJoon** [comment]
저도 위와 같은 오류가 발생하였습니다. 현재 앱이 죽는다기보다는 빨간색 에러가 뜨면서 저런 메시지가 나오는 상황입니다.

**Comment by heyman333** [comment]
@LeeKyungJoon 안녕하세요. 저 에러메제시가 로그캣에 찎히는건지 자바스크립트단에서 찍히는건지는 다시 한번 확인해 보겠습니다~
하지만 개발자또는 회사에사 사용자에게 이메일을 요청한다고 해서 사용자가 이메일을 넘겨줄 의무는 없습니다.
이메일을 필수로 하려면 별도의 검수요청을 받아야 합니다.

**Comment by peacel** [comment]
const getKakaoProfile = () => {
    logCallback('Get Profile Start', setKakaoProfileLoading(true));

    KakaoLogins.getProfile()
      .then(result => {
        setKakaoProfile(result);
        logCallback(
          `Get Profile Finished:${JSON.stringify(result)}`,
          setKakaoProfileLoading(false),
        );
      })
      .catch(err => {
        logCallback(
          `Get Profile Failed:${err.code} ${err.message}`,
          setKakaoProfileLoading(false),
        );
      });
  };

위의 부분에서 err를 catch해서 "Get Profile Failed:E_UNKOWN Attempt to invoke virtual method 'java.lang.String com.kakao.usermgmt.response.model.Profile.getNickname()' on a null object reference" 메시지가 콘솔 로그로 찍힙니다.

-> 보여주신 화면 이미지처럼, id는 나오고 email이 null이라도 나왔으면 하는데요. 저는 프로파일 정보를 전혀 가져오지 못하고 있습니다 ^^;;

**Comment by LeeKyungJoon** [comment]
@heyman333  안녕하세요. 답변 감사합니다. 우선, 개발자님께서 알려주신 답변으로 저희 회사 측에서 확인한 결과 이메일을 사용하는 것이 아닌 id를 사용하는 것으로 변경하였습니다만 @peacel 님과 같은 결과를 보여주고 있어 id 조차 사용하지 못하는 상황입니다. 현재 유일하게 가져올 수 있는 것을 login을 통한 토큰과 만료일, refresh토큰 뿐입니다. 참고로 저 에러는 로그캣에서 찍히고 있습니다.

**Comment by heyman333** [comment]
@LeeKyungJoon @peacel 아 무슨말씀이신지 잘 알겠습니다. 이번주중에 확인하고 이상이 있을경우 수정하겠습니다.

**Comment by heyman333** [comment]
@LeeKyungJoon @peacel 두분다 iOS는 잘 동작하시는건가요?

**Comment by LeeKyungJoon** [comment]
@heyman333 네 iOS 에서는 잘 작동하는거 확인했습니다.

**Comment by Eumhongin** [comment]
> @heyman333 네 iOS 에서는 잘 작동하는거 확인했습니다.

혹시 iOS동작 할때 세팅 어떻게 되있는지 알수있을까요?

**Comment by peacel** [comment]
> @LeeKyungJoon @peacel 두분다 iOS는 잘 동작하시는건가요?

저는 안드로이드OS에서만 체크하고 있습니다.

**Comment by LeeKyungJoon** [comment]
@Eumhongin 현재 iOS에서 세팅은 Pod install을 사용하였고, 개발자님께서 올리신 방법대로 AppDelegate.m에 코드를 그대로 복붙한 상태입니다. 그리고 RN 버전은 "0.61.5" 이며, 패키지에 있는 카카오 버전은 "^2.4.5"을 사용 중입니다. 코드는 다음과 같습니다.
const KakaoTalk = () => {
    //KakaoLogins.logout()
    //  .then(result => {
    //    console.log('logout');
    //  })
    //  .catch(err => {
    //    console.log('error', err);
    //  });
    KakaoLogins.login()
      .then(result => {
        KakaoLogins.getProfile()
          .then(result => {
            console.log('TTTTT', result.id);
          })
          .catch(err => {
            console.log(`Get Profile Failed:${err.code} ${err.message}`);
          });
        console.log('TTTTTT', result);
      })
      .catch(err => {
        if (err.code === 'E_CANCELLED_OPERATION') {
          console.log('KakaoTalk -> err.message', err.message);
        } else {
          console.log(
            'KakaoTalk -> `Login Failed:${err.code} ${err.message}`',
            `Login Failed:${err.code} ${err.message}`
          );
        }
      });
  };

**Comment by heyman333** [comment]
@LeeKyungJoon 혹시 안드로이드 에뮬레이터에서는 에러가 발생하지 않으시나요?
저도 지금 새로운 프로젝트를 만들고 위와 같은 경우에 대해서 테스트 해보고 있는데 다음처럼 안드로이드 LogCat에 필요한 데이터가 잘 들어오네요 (이메일을 선택으로 두고 이메일을 체크 하지 않았습니다)

제가 안드로이드 기기가 없어서 지금 딱히 테스트 해볼 방법이 없네요 ㅠㅠ 에뮬레이터에서 한번 확인해 주시면 감사하곘습니다. 빨리 해결 됐으면 좋겠네요
