### ISSUE TITLE
녹스 플레이어에서 로그인 또는 기타 버튼 클릭 시 RnKakaoLgins.login 찾을 수 없다고 나오네요.

### ISSUE THREAD

**Issue by yoojeen126** [react-native-seoul/react-native-kakao-login#142]
### Version of kakao-login libraries

KAKAO_SDK_GROUP=com.kakao.sdk
KAKAO_SDK_VERSION=1.27.0

### Version of react-native

"react": "16.11.0",
"react-native": "0.62.2",

### Platforms you faced the error (IOS or Android or both?)

Android

### Actual behavior

RnKakaoLgins.login 찾을 수 없다고 나오네요.

### Tested environment (Emulator? Real Device?)

녹스 플레이어에서 테스트 하고 있습니다. 실제 기기에서 하면 또 다르나요?

**Comment by yoojeen126** [comment]
원인 찾았습니다. 설치 시 node_module/android에 버전 문제인지 모르겠지만 자바 파일 들이 없이 설치 되네요 .
KakaoSDKAdapter.java, RNkakaoLoginsModule.java, RnkakaoLoginsPackage.java 이 세개 파일이 없었습니다.
수동으로 추가 하니까 제대로 됩니다.

**Comment by heyman333** [comment]
@yoojeen126 네 확인감사합니다. 추후에 확인해보고 수정사항이 있으면 업데이트 하겠습니다!
