### ISSUE TITLE
IOS 로그인시 앱꺼짐 - 'NSInvalidArgumentException'

### ISSUE THREAD

**Issue by Eumhongin** [react-native-seoul/react-native-kakao-login#143]
### Version of kakao-login libraries

1.21.1

### Version of react-native

0.62.2

### Platforms you faced the error (IOS or Android or both?)

iOS

### Expected behavior

로그인 하면 값을 받아와야함

### Actual behavior

로그인 버튼 클릭시 어플리케이션 셧다운됨

### Tested environment (Emulator? Real Device?)

Emulator iPhone 11 (13.5)

### Error log

> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[4]'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e3cf0e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50ba89b2 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23ecfa51 _CFThrowFormattedException + 194
	3   CoreFoundation                      0x00007fff23eda4a6 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:].cold.4 + 38
	4   CoreFoundation                      0x00007fff23e9b787 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 247
	5   CoreFoundation                      0x00007fff23e38e11 +[NSDictionary dictionaryWithObjects:forKeys:count:] + 49
	6   socialLoginProject                  0x000000010b63ba13 __32-[RNKakaoLogins login:rejecter:]_block_invoke + 867
	7   socialLoginProject                  0x000000010b6b35cb __27-[KOSession startAuthrize:]_block_invoke_3 + 217
	8   socialLoginProject                  0x000000010b6bd429 __56+[KOToken tokenTaskWithAuthCode:redirectUri:completion:]_block_invoke + 706
	9   socialLoginProject                  0x000000010b1a7077 __79+[FLEXNetworkObserver asyncCompletionWrapperForRequestID:mechanism:completion:]_block_invoke + 1367
	10  CFNetwork                           0x00007fff22f5a4d0 CFNetwork + 38096
	11  CFNetwork                           0x00007fff22f6d740 _CFHTTPMessageSetResponseProxyURL + 17217
	12  Foundation                          0x00007fff2592128c __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	13  Foundation                          0x00007fff259211ad -[NSBlockOperation main] + 80
	14  Foundation                          0x00007fff259240dc __NSOPERATION_IS_INVOKING_MAIN__ + 17
	15  Foundation                          0x00007fff259203ee -[NSOperation start] + 731
	16  Foundation                          0x00007fff25924a20 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 17
	17  Foundation                          0x00007fff25924540 __NSOQSchedule_f + 182
	18  libdispatch.dylib                   0x000000010e16a4dc _dispatch_block_async_invoke2 + 83
	19  libdispatch.dylib                   0x000000010e15be8e _dispatch_client_callout + 8
	20  libdispatch.dylib                   0x000000010e169d97 _dispatch_main_queue_callback_4CF + 1149
	21  CoreFoundation                      0x00007fff23da0909 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	22  CoreFoundation                      0x00007fff23d9b459 __CFRunLoopRun + 2041
	23  CoreFoundation                      0x00007fff23d9a944 CFRunLoopRunSpecific + 404
	24  GraphicsServices                    0x00007fff38ba6c1a GSEventRunModal + 139
	25  UIKitCore                           0x00007fff48c8b9ec UIApplicationMain + 1605
	26  socialLoginProject                  0x000000010ad34e10 main + 112
	27  libdyld.dylib                       0x00007fff51a231fd start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by pekosong** [comment]
저도 동일한 증상입니다.

**Comment by heyman333** [comment]
혹시 두분다 cd ios => pod install 까지 질행하신건가요~?

**Comment by pekosong** [comment]
네 로그인 모달 뜨고 카카오 로그인 성공 후 다시 앱으로 돌아오면서 튕기네요.

**Comment by heyman333** [comment]
@pekosong 실제 실행하신 js 또는 ts파일을 같이 올려주시면 감사하겠습니다.

**Comment by Eumhongin** [comment]
> @pekosong 실제 실행하신 js 또는 ts파일을 같이 올려주시면 감사하겠습니다.

금방 올려드리겠습니다!
