### ISSUE TITLE
RN 0.63 에서 iOS KakaoLogin SDK 설정 이슈

### ISSUE THREAD

**Issue by Ghun2** [react-native-seoul/react-native-kakao-login#146]
### Version of kakao-login libraries

"@react-native-seoul/kakao-login": "^2.5.0"

### Version of react-native

"react-native": "0.63.0"

### Platforms you faced the error (IOS or Android or both?)

Post installation (important)
iOS
Framework 설정
[Build Settings] > [Linking] > [Other Linker Flags]에 
-all_load 또는
-force_load \$(SRCROOT)/KakaoOpenSDK.framework/KakaoOpenSDK를 
추가에서 에러발생

### Actual behavior

(RN 0.63) 카카오 공식문서대로 SDK 설치를 하게되면 ios 빌드과정에서 에러발생

RN 0.63.0 에서 Kakao iOS SDK 설정 공식 문서 나와있는
[Build Settings] > [Linking] > [Other Linker Flags]에 
-all_load 또는
-force_load \$(SRCROOT)/KakaoOpenSDK.framework/KakaoOpenSDK
추가 하는 부분을 스킵해야합니다. 

다른분들도 알 수 있도록
README.md 에 위의 이슈 해결방법 추가해주세요.

**Comment by heyman333** [comment]
@Ghun2 감사합니다! 확인해보고 적용할게요!

**Comment by hyochan** [comment]
`3.0.1` 이후 버전을 사용하시고 문제가 생기시면 알려주시기 바랍니다 :pray:
