### ISSUE TITLE
안드로이드 컴파일 오류 있습니다.

### ISSUE THREAD

**Issue by jihokim2** [react-native-seoul/react-native-kakao-login#149]
### Version of kakao-login libraries

2.6.0

### Version of react-native

0.63.1

### Platforms you faced the error (IOS or Android or both?)

android

### Expected behavior

정상적인 빌드

### Actual behavior

컴파일 오류

node_modules/@react-native-seoul/kakao-login/android/src/main/java/com/dooboolab/kakaologins/RNKakaoLoginsModule.java:357: error: cannot find symbol
    private void updateScopes(final ReadableArray scopes, final Promise promise) {
                                    ^
  symbol:   class ReadableArray
  location: class RNKakaoLoginsModule
/Users/jhkim/albam-connect/node_modules/@react-native-seoul/kakao-login/android/src/main/java/com/dooboolab/kakaologins/RNKakaoLoginsModule.java:366: error: cannot find symbol
            public void onAccessTokenReceived(AccessToken accessToken) {
                                              ^
  symbol: class AccessToken
2 errors

FAILURE: Build failed with an exception.

### Tested environment (Emulator? Real Device?)
안드로이드 전부 다 입니다.

**Comment by heyman333** [comment]
일단은 배포 전까지 2.5.0 사용부탁 드리겠습니다 👍
