### ISSUE TITLE
여전히 iOS에서 카카오 로그인을 실행하면 확인다음 앱이 꺼집니다.

### ISSUE THREAD

**Issue by Eumhongin** [react-native-seoul/react-native-kakao-login#153]
## package.json
"@react-native-seoul/kakao-login": "^2.6.0",

## Error Message
<img width="692" alt="스크린샷 2020-07-17 오후 4 02 20" src="https://user-images.githubusercontent.com/23710025/87758210-ff9d8280-c846-11ea-84f6-eb1cfa8f7645.png">

## AppDelegate.m
<img width="1197" alt="스크린샷 2020-07-17 오후 4 03 46" src="https://user-images.githubusercontent.com/23710025/87758260-1ba12400-c847-11ea-9a8b-4e7ecbdfb19b.png">

**Comment by heyman333** [comment]
#151 이 아직 배포가 안되었씁니다. 배포 되고 다시 실행해주세요 ㅠ 빨리 배포 하겠습니다.

**Comment by heyman333** [comment]
@Eumhongin 아니면 저희 마스터 브랜치를 직접 다운받아서 쓰셔도됩니다

**Comment by Eumhongin** [comment]
> @Eumhongin 아니면 저희 마스터 브랜치를 직접 다운받아서 쓰셔도됩니다

아 배포되면 사용하겠습니다! 감사합니다 :) 제가 아직 깃헙 초보라 ㅠㅠ 기다리겠습니다!

**Comment by heyman333** [comment]
@Eumhongin 2.7.0 사용 해보세요~ 확인해보시고 이상 없으면 이슈 닫겠습니다!
