### ISSUE TITLE
안드로이드 릴리즈 키해시 추출 에러

### ISSUE THREAD

**Issue by huurray** [react-native-seoul/react-native-kakao-login#158]
### Version of kakao-login libraries

2.5.0

### Version of react-native

0.62.2

### Platforms you faced the error (IOS or Android or both?)

안드로이드

### Expected behavior

로그인 정상작동

### Actual behavior

개발은 맥을 사용중에 있고, 현재 apk를 빌드하여 안드로이드 실기기 테스트를 진행 중입니다.
(개발 모드에서 모두 정상작동)

앱이름.keystore 파일을 생성하였고, ~/Library/dev/project/앱이름/android/app/앱이름.keystore 에 위치시켰습니다.

그리고 키해시값을 등록하기위해 

https://developers.kakao.com/docs/latest/ko/getting-started/sdk-android-v1#key-hash

위 문서를 참고하여,

keytool -exportcert -alias 앱이름 -keystore ~/Library/dev/project/앱이름/android/app/앱이름.keystore | openssl sha1 -binary | openssl base64

명령어를 실행하였고 나온값을 카카오 개발자 콘솔에 등록하였는데,
기기에서 카카오 로그인이 되지 않아서 질문드립니다.

저렇게 추출하는 것이 맞을까요? 
아니면 android/app 폴더 안에 있는 keystore에서 키해시 추출하는 방법이 다른게 있을까요??

읽어주셔서 감사합니다.

### Tested environment (Emulator? Real Device?)

안드로이드 실제 기기

**Comment by heyman333** [comment]
@huurray 
릴리즈 빌드할때 사용하는 키스토어가 있을텐데 그 키스토어에 해쉬값을 등록해야 합니다. 
보통 안드로이드는 개발용키스토어, 릴리즈 키스토어 2개를 같이 등록합니다.

**Comment by huurray** [comment]
@heyman333 
제가 맥에서의 경로를 착각했었습니다. 
~/Library/dev/project/앱이름/android/app/앱이름.keystore 가아니라
~/dev/project/앱이름/android/app/앱이름.keystore 였습니다.

현재 정상 작동합니다. 감사합니다.
