### ISSUE TITLE
카카오 로그인시 오류 발생하는 문제 있습니다.

### ISSUE THREAD

**Issue by jihokim2** [react-native-seoul/react-native-kakao-login#166]
### Version of kakao-login libraries

2.10.0

### Version of react-native

0.63.2

### Platforms you faced the error (IOS or Android or both?)

android

### Expected behavior

특정 값이 없어도 로그인이 정상적으로 되어야 됩니다.

### Actual behavior

현재 ageRange를 저희는 받고 있지 않습니다. 하지만 안드로이드에서는 kakaoAccount.getAgeRange().getValue() 이 부분에서
Null pointer exception이 나면서 카카오 로그인이 정상동작하지 않습니다.

### Tested environment (Emulator? Real Device?)
실제 기기 입니다.

**Comment by heyman333** [comment]
@jihokim2 네 감사합니다. 일단은 [2.9.0]버전 사용 부탁드립니다 이번에 업데이트 된 기능에 문제가 있는거같네요!

**Comment by heyman333** [comment]
@jeongjhs 이거 혹시 확인가능할까요?ㅠㅠ
