### ISSUE TITLE
iOS에서 간편 로그인 화면이 뜨지 않습니다.

### ISSUE THREAD

**Issue by JoonDong2** [react-native-seoul/react-native-kakao-login#168]
### Version of kakao-login libraries

2.10.0

### Version of react-native

.63.2

### Platforms you faced the error (IOS or Android or both?)

iOS 13.6

### Expected behavior

iOS에 카카오톡이 정상적으로 설치되어 동작하고 있기 때문에, `KakaoLogins.login`을 실행하였을 때, 검은색 배경화면에 간편 로그인 버튼이 있는 스크린이 나타날 것으로 예상했습니다.

안드로이드에서는 간편 로그인 화면이 나타납니다.

### Actual behavior

iOS에 카카오톡이 정상적으로 설치되어 동작하고 있는데, `KakaoLogins.login`을 실행하였을 때, **항상 웹뷰 로그인 스크린만 나타납니다.**

### Tested environment (Emulator? Real Device?)

아이폰6s

**Comment by heyman333** [comment]
혹시 이것도 해보셨나요?

```
KakaoLogins.login([KAKAO_AUTH_TYPES.Talk]);
```

**Comment by JoonDong2** [comment]
> 혹시 이것도 해보셨나요?
> 
> ```
> KakaoLogins.login([KAKAO_AUTH_TYPES.Talk]);
> ```

예.. 시도해 봤습니다..

**Comment by heyman333** [comment]
@floydkim 갑작스러운 소환 죄송합니다....ㅠㅠ 이거 확인한번만 부탁 드리겠습니다ㅠㅠ

**Comment by heyman333** [comment]
@floydkim @JoonDong2 

![ezgif com-resize](https://user-images.githubusercontent.com/22214150/91300470-47b4ab00-e7de-11ea-9817-06f831a5184c.gif)

```js
  const kakaoLogin = () => {
    logCallback('Login Start', setLoginLoading(true));

    KakaoLogins.login([KAKAO_AUTH_TYPES.Talk])
      .then(result => {
        setToken(result.accessToken);
        logCallback(
          `Login Finished:${JSON.stringify(result)}`,
          setLoginLoading(false),
        );
      })
      .catch(err => {
        if (err.code === 'E_CANCELLED_OPERATION') {
          logCallback(`Login Cancelled:${err.message}`, setLoginLoading(false));
        } else {
          logCallback(
            `Login Failed:${err.code} ${err.message}`,
            setLoginLoading(false),
          );
        }
      });
  };
```
전 이렇게 테스트 했구요 바로 카카오로 잘 넘어가는거 확인됐습니다... 버전을 타는 문제일수도 있겠네요
전 iOS13.5.1입니다

**Comment by floydkim** [comment]
넵 한번 확인해볼게요

**Comment by floydkim** [comment]
@JoonDong2 

혹시 info.plist에 `kakaokompassauth` 추가 하셨나요?

https://developers.kakao.com/docs/latest/ko/getting-started/sdk-ios-v1
문서 최하단 참고 부탁드립니다!

**Comment by JoonDong2** [comment]
> @JoonDong2
> 
> 혹시 info.plist에 `kakaokompassauth` 추가 하셨나요?
> 
> https://developers.kakao.com/docs/latest/ko/getting-started/sdk-ios-v1
> 문서 최하단 참고 부탁드립니다!

예.. 추가했습니다.

일단 처음부터 다시 적용해보고 있습니다.

**Comment by JoonDong2** [comment]
> @JoonDong2
> 
> 혹시 info.plist에 `kakaokompassauth` 추가 하셨나요?
> 
> https://developers.kakao.com/docs/latest/ko/getting-started/sdk-ios-v1
> 문서 최하단 참고 부탁드립니다!

 처음부터 차근차근 다시 해 보니까 되네요.
밤 늦게 귀찮게 해드려서 죄송합니다..

**Comment by JoonDong2** [comment]
> @floydkim 갑작스러운 소환 죄송합니다....ㅠㅠ 이거 확인한번만 부탁 드리겠습니다ㅠㅠ
> 일단 저도 디바이스에서 한번 테스트 해보겠습니다!

처음부터 다시 해 보니까 됩니다.
제가 중간에 뭔가 빠뜨렸던거 같네요.

귀찮게 해 드려서 죄송합니다..

**Comment by floydkim** [comment]
해결 되셨다니 다행입니다! 😃

**Comment by heyman333** [comment]
@floydkim 감사합니다 ㅠ.ㅠ 저게 누락 되어있어서 그런거였군요 수고하셨습니다 👍

**Comment by daheeahn** [comment]
> @JoonDong2
> 
> 혹시 info.plist에 `kakaokompassauth` 추가 하셨나요?
> 
> https://developers.kakao.com/docs/latest/ko/getting-started/sdk-ios-v1
> 문서 최하단 참고 부탁드립니다!

저도 이게 빠져있어서 간편로그인이 안됐었네요. 감사합니다!
