### ISSUE TITLE
ios 로그인이 안됩니다

### ISSUE THREAD

**Issue by britny-no** [react-native-seoul/react-native-kakao-login#175]
### Version of kakao-login libraries

"@react-native-seoul/kakao-login": "^2.10.1",

### Version of react-native

   "react-native": "0.63.3",

### Platforms you faced the error (IOS or Android or both?)

ios

### Expected behavior

클릭후 로그인 페이지로 이동해야합니다

### Actual behavior

로그인 클릭시 로딩만 됩니다. 아무 에러없이 진행이 안됩니다

### Tested environment (Emulator? Real Device?)

iphone 11에뮬레이터입니다

**Comment by heyman333** [comment]
```
공식문서 - 개발 프로젝트 설정 을 참고하여 info.plist, URL Types 및 커스텀 스킴 추가 등 기타 필요한 세팅들을 프로젝트에 추가해줍니다.
```
README.md 파일에 위 설정이 제대로 되었는지 한번만 더 확인해 주시면 감사하곘습니다.
그리고 xcode에 에러메세지 로그가 찍힐 수 있는데, 그쪽도 한번 확인해보시면 정확한 에러메세지를 확인 하실 수 있습니다!

**Comment by britny-no** [comment]
아 다 했는데 에러도 안뜨고 계속 로딩만 진행되네요...ㅜㅜ 안드로이드는 되는데 ios가 힘드네요ㅜ

2020년 10월 13일 (화) 오전 1:21, Yeongsu Han <notifications@github.com>님이 작성:

**Comment by heyman333** [comment]
@britny-no 자바스크립트 말고 xcode에서 찍히는 로그도 다 확인하신거죠?ㅠ

**Comment by britny-no** [comment]
네넵 ㅜㅜ 오히려 빨간색이 보고싶네요... 그런데
https://www.npmjs.com/package/@actbase/react-native-kakao-login
이 패키징 수정해서 하니까 되네요. 일단 감사합니다! 덕분에 안드로이드는 금방 했었어요.

2020년 10월 13일 (화) 오후 5:35, Yeongsu Han <notifications@github.com>님이 작성:

**Comment by heyman333** [comment]
@britny-no 아 카카오 로그인 모듈이 또 생겼네요 https://www.npmjs.com/package/@actbase/react-native-kakao-login
혹시 iOS14에서 진행하시나요?

**Comment by heyman333** [comment]
@britny-no 저도 다시 테스트 해보고 같은문제 발생시 해결하고 알려드리곘습니다~

**Comment by britny-no** [comment]
넵넵 감사합니다! 아니요! ios 11이었어용

2020년 10월 13일 (화) 오전 2:01, Yeongsu Han <notifications@github.com>님이 작성:

**Comment by heyman333** [comment]
추후에 크게 이슈레이징이 안되고 있는 상황이라 클로즈 하겠습니다!
