### ISSUE TITLE
VerifyReleaseResources FAILED error on releasing an APK

### ISSUE THREAD

**Issue by augini** [react-native-seoul/react-native-kakao-login#180]
#### I am receving below error everytime I release an apk. APK is working fine but I want to stop getting this error on building an APK.

" > Task :react-native-seoul-kakao-login:verifyReleaseResources FAILED
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions "

**Comment by heyman333** [comment]
You resolve this issue in #179. right?

**Comment by augini** [comment]
Yes, thank you for merging my PR.
That should solve the issue.
I will close this issue.
