### ISSUE TITLE
iOS xcode archive error "use of undeclared identifier "KOSession""

### ISSUE THREAD

**Issue by jungsunwoung** [react-native-seoul/react-native-kakao-login#182]
### Platforms you faced the error (IOS or Android or both?)

IOS

### Expected behavior

아카이빙이 정상적으로 되야함

### Actual behavior

기기에서 정상작동(로그인) 다 하고 그 이후에 앱스토어 등록을 위해서 archive를 하는 과정에서 use of undeclared identifier "KOSession"이라고 뜨면서 appdelegate.m에 추가했던 KOSession 부분에 모두 빨간줄이 생겼습니다.

### Tested environment (Emulator? Real Device?)

에뮬레이터와 실제기기 모두

**Comment by heyman333** [comment]
Version of kakao-login libraries
Version of react-native

두개 명시 해주시면 테스트 해보곘습니다

**Comment by heyman333** [comment]
https://devtalk.kakao.com/t/use-of-undeclared-type-kosession/60264
여기도 한번 참고 해보세요~

**Comment by jungsunwoung** [comment]
kakao-login : 2.10.1
react-native :0.63.1
입니다

그런데 하루종일 안되다가 다음날 자고일어났는데 해결이 됐습니다.. 중간에 캐시를 지우고 몇번 해보긴 했는데 해결은 됐지만 근본적인 해결책은 무엇인지 잘 모르겠네요 ㅠㅠ

**Comment by jungsunwoung** [comment]
저만 이런 이슈를 겪은 것 같아서 글 닫겠습니다ㅠㅠ
