### ISSUE TITLE
Login, Logout error in Android 11

### ISSUE THREAD

**Issue by JeffGuKang** [react-native-seoul/react-native-kakao-login#185]
### Version of kakao-login libraries

2.10.2

### Version of react-native

0.61.5

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

Login and Logout are not working well.

### Actual behavior

**Logout**

```
import RNKakao from '@react-native-seoul/kakao-login'
...
await RNKakao.logout()
```

```sh
kakao logout error Error: Could not refresh access token.
    at Object.fn [as logout] (NativeModules.js:99)
    at Object.logout (index.js:94)
    at _callee2$ (xxxxxx.tsx:48)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at tryCatch (runtime.js:63)
    at invoke (runtime.js:154)
    at runtime.js:164
    at tryCallOne (core.js:37)
```

**Login**

Infinity loading as screenshot

![image](https://user-images.githubusercontent.com/216363/107300841-9a98cb00-6abd-11eb-891a-cee10609211c.png)

### Tested environment (Emulator? Real Device?)

Real device 

Android 11

**Comment by JeffGuKang** [comment]
Official docs 

https://developers.kakao.com/docs/latest/ko/sdk-download/android

> 2.0.4 | 2020.10.20 | * Android Studio 요구사양 3.6.1 이상으로 변경 * 버그 수정   - Android 11 이상 타게팅 시 카카오톡 간편로그인 등 외부 패키지 사용 불가능 현상 대응

I am trying to apply latest Kakao sdk version. 2.3.0

**Comment by JeffGuKang** [comment]
Working well now. May my project has some setting issue.

**Comment by JeffGuKang** [comment]
Example is working well.

**Comment by heyman333** [comment]
dialog를 쓰는 경우는 폰에 카카오톡이 설치 되지 않았을때 인가요?

**Comment by ewlkkf** [comment]
라이브러리 2.10.2, rn 0.63.2 에서도 무한 로딩 현상이 발생합니다.
S20+ Android 11 인데, 로그인 함수를 호출하면 이 함수가 끝나지 않습니다.

KakaoLogins.login([], (err, token) => {}); 방식으로만 해야 하는 건가요?
KakaoLogins.login([]).then().catch() 방식은 안되는 건가요?

**Comment by kimnagui** [comment]
카카오개발자 사이트에서 Android 플랫폼 "키 해시" 에다가 
Google Play Console -> 설정 -> 앱 무결성 -> SHA-1 값을 
```cmd
echo SHA-1값 | xxd -r -p | openssl base64
```
로 변환하고 넣어보세요

**Comment by JeffGuKang** [comment]
> 라이브러리 2.10.2, rn 0.63.2 에서도 무한 로딩 현상이 발생합니다.
> S20+ Android 11 인데, 로그인 함수를 호출하면 이 함수가 끝나지 않습니다.
> 
> KakaoLogins.login([], (err, token) => {}); 방식으로만 해야 하는 건가요?
> KakaoLogins.login([]).then().catch() 방식은 안되는 건가요?

`kakaoInfo = await KakaoLogins.login([KAKAO_AUTH_TYPES.Talk])`
식으로 해보시면 어떠신가요? dialog를 호출하게 할 경우 전 무한 로딩이 생겼었습니다.

**Comment by JeffGuKang** [comment]
> dialog를 쓰는 경우는 폰에 카카오톡이 설치 되지 않았을때 인가요?

설치되어 있을때도 발생했습니다.

**Comment by hyochan** [comment]
`3.0.1` 이후 버전을 사용하시고 문제가 생기시면 알려주시기 바랍니다 :pray:
