### ISSUE TITLE
안드로이드 로그인 화면이 상태바에 가려지는 현상

### ISSUE THREAD

**Issue by theseung** [react-native-seoul/react-native-kakao-login#186]
### Version of kakao-login libraries

2.10.2

### Version of react-native

0.63.4

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

안드로이드에서 로그인 화면이 상태바로 부터 분리되어 정상 출력되어야 합니다.

### Actual behavior

안드로이드에서 로그인 화면이 상태바로 인해 가려집니다.
(문제 화면  [스크린샷](https://ifh.cc/g/5Cuk1D.jpg)

### Tested environment (Emulator? Real Device?)

갤럭시 노트20  울트라 / 안드로이드 버전 11

**Comment by hyochan** [comment]
`3.0.1` 이후 버전을 사용하시고 문제가 생기시면 알려주시기 바랍니다 :pray:
