### ISSUE TITLE
iOS에서 일부 profile 정보 null로 받아오는 현상

### ISSUE THREAD

**Issue by dayoul** [react-native-seoul/react-native-kakao-login#192]
### Version of kakao-login libraries

3.01

### Version of react-native

0.61.5

### Platforms you faced the error (IOS or Android or both?)

iOS

### Expected behavior

로그인 후 getProfile을 통해 프로필 정보를 요청하면 kakao 콘솔에 허용해 놓은 정보가 받아진다.

### Actual behavior

같은 카카오 계정으로 로그인 후 프로필 정보를 요청하면 android는 nickname, profileImageUrl, email, gender, birthday, ageRange 모두 잘 받아오지만 iOS에서는 nickname, email, birthday만 오고 profileImageUrl, gender, ageRange는 null로 받아짐.
*참고로 scope은 "scopes":["age_range","birthday","account_email","gender","profile"] 로 잘 반환되고 있습니다. 

### Tested environment (Emulator? Real Device?)
Emulator iPhone 11 Pro Max 13.7, 14.3
Real device iPhone 7 14.4.1
모두 동일하게 재현됨.

+위 이슈와 더불어 iOS의 경우 email 정보를 사용자가 허용하지 않고 로그인했을때, 앱이 crush되는 현상이 있습니다. 
try catch로도 잡히지 않고 앱이 튕기는 현상입니다. 

아래는 현재 카카오 콘솔에서의 동의 항목 설정 현황입니다.

![스크린샷 2021-03-22 오후 10 21 25](https://user-images.githubusercontent.com/62198393/111996510-6f45d900-8b5d-11eb-933c-73ccce99a4f8.png)

**Comment by hyochan** [comment]
Crash 됐을 때 로그를 찍어서 공유해주시면 감사하겠습니다 :)

**Comment by dayoul** [comment]
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file kakao_login/RNKakaoLogins.swift, line 138

코드상      "email": user?.kakaoAccount?.email! as Any, -> 이 부분 인듯합니다.

**Comment by hyochan** [comment]
이슈 리포트 감사합니다. 수정 사항은 [3.0.2](https://github.com/react-native-seoul/react-native-kakao-login/releases/tag/3.0.2) 에 반영 되었습니다. 계속 문제가 발생하면 이슈보드를 새로 생성해주세요 🙏

**Comment by AMaster124** [comment]
3.0.7에서 아이폰인 경우 email과 id를 제외한 모든 정보들이 null로 얻어집니다. 안드로이드는 잘 되는데 확인 부탁드립니다.
![Screenshot 2021-05-01 at 06 09 37](https://user-images.githubusercontent.com/66033254/116755076-d734ec80-aa44-11eb-9cbf-1a124c9b1452.png)
