### ISSUE TITLE
Android assembleRelease시 로그인 이후 앱 크래시

### ISSUE THREAD

**Issue by fifthsage** [react-native-seoul/react-native-kakao-login#201]
### Version of kakao-login libraries

3.0.3

### Version of react-native

61.5

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

로그인 완료 이후 토큰 리턴

### Actual behavior

로그인 완료 이후 앱 크래시

### Tested environment (Emulator? Real Device?)

SM-G973M

### Attached
```bash
03-30 01:12:25.588 16024 16024 E AndroidRuntime: ClientError(reason=TokenNotFound, msg=Refresh token not found in the response.)
03-30 01:12:25.588 16024 16024 E AndroidRuntime: 	at com.kakao.sdk.auth.k.c$a.a(Unknown Source:139)
03-30 01:12:25.588 16024 16024 E AndroidRuntime: 	at com.kakao.sdk.auth.k.c$a.b(Unknown Source:5)
03-30 01:12:25.588 16024 16024 E AndroidRuntime: 	at com.kakao.sdk.auth.b$d.b(Unknown Source:33)
03-30 01:12:25.588 16024 16024 E AndroidRuntime: 	at j.g$b$a$a.run(Unknown Source:37)
03-30 01:12:25.588 16024 16024 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
03-30 01:12:25.588 16024 16024 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-30 01:12:25.588 16024 16024 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
03-30 01:12:25.588 16024 16024 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8506)
03-30 01:12:25.588 16024 16024 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-30 01:12:25.588 16024 16024 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
03-30 01:12:25.588 16024 16024 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by fifthsage** [comment]
iOS도 상용 빌드에서  카카오 로그인 이 후 크래시가 발생하지는 않지만 제대로 동작하지 않습니다

**Comment by hyochan** [comment]
흠. 현재 상용에서 잘 쓰고 있습니다만 크래쉬 이슈가 없었습니다. 해결에 도움이 되는 추가적인 정보 혹은 재현이 되는 다른 분들을 기다려봐야할 것 같습니다.

리드미를 꼼꼼히 보셨는지 체크해주시면 감사하겠습니다.

**Comment by fifthsage** [comment]
android의 경우 proguard-rules.pro에 다음과 같은 라인을 추가해주면 release 빌드에서도 크래시를 해결 할 수 있었습니다.

```
-keep class com.kakao.sdk.**.model.* { <fields>; }
```

**Comment by Inbeom-Lee** [comment]
안녕하세요,
현재 React Native로 개발 중인 앱에서 Kakao SDK를 사용하는 도중, Release 빌드에서 크래시가 발생하고 있습니다.

ProGuard 규칙에 다음과 같은 내용을 추가했습니다:
`-keep class com.kakao.sdk.**.model.* { <fields>; }`
minifyEnabled와 shrinkResources를 활성화한 상태에서 앱을 실행하면 런타임 크래시가 발생합니다.
다만, minifyEnabled false로 설정하면 크래시는 사라지지만, 이는 최적화 문제로 인해 사용을 지양하려고 합니다.

확인한 사항:
1. ProGuard 규칙에 위 내용을 추가한 이후에도 크래시가 해결되지 않았습니다.
2. adb logcat을 통해 크래시 로그를 확인했으나, Obfuscation으로 인해 상세 원인을 파악하기 어렵습니다.

혹시 ProGuard와 Kakao SDK를 함께 사용할 때 추가적으로 필요한 설정이나 확인해야 할 사항이 있을까요?

**Comment by tinker-dev-monk** [comment]
@Inbeom-Lee 
안녕하세요, 
혹시 해당 문제 하셨을까요.
저의 경우 로그인 화면까지는 잘 뜨나 로그인을 누르면 크래시가 발생합니다.
동일하게 ProGuard 등 설정되어있는 상태입니다.

**Comment by Inbeom-Lee** [comment]
> [@Inbeom-Lee](https://github.com/Inbeom-Lee) 안녕하세요, 혹시 해당 문제 하셨을까요. 저의 경우 로그인 화면까지는 잘 뜨나 로그인을 누르면 크래시가 발생합니다. 동일하게 ProGuard 등 설정되어있는 상태입니다.

release 버전에서의 키 해시 문제였습니다. 빌드전에 MainActivity.kt 안에 key hash 찍는 코드 넣어두시고 안드로이드 스튜디오에서 release버전 실행하여 키해시 확인 후 추가하니 문제 해결 되었습니다.
`
import com.kakao.sdk.common.util.Utility 

val keyHash = Utility.getKeyHash(this)
Log.d("KeyHash", "Key Hash: $keyHash")
`

**Comment by tinker-dev-monk** [comment]
@Inbeom-Lee 

말씀 감사합니다.
추가적으로 확인해보니 `retrofit2` 난독화 관련 문제도 있어 아래 내용을 추가적으로 ProGuard 추가하니 해결되었습니다.

```
-keep class retrofit2.** { *; }
-keepattributes *Annotation*
```

[관련 내용](https://devtalk.kakao.com/t/method-authapi-issueaccesstoken/130860/3)
