### ISSUE TITLE
KAKAO_APP_KEY가 암호화??되는 현상

### ISSUE THREAD

**Issue by iKoru** [react-native-seoul/react-native-kakao-login#205]
### Version of kakao-login libraries

3.0.4
### Version of react-native

0.63.4
### Platforms you faced the error (IOS or Android or both?)

iOS
### Expected behavior

인증 완료 후 앱으로 리다이렉트가 정상적으로 돼야함
### Actual behavior

#193 여기서 나는 오류와 같은 오류가 나서 확인해보니, 
추가해준 조건문에 
`[RNKakaoLogins isKakaoTalkLoginUrl:url]`
부분이 false가 나오더라구요. 이상해서 KAKAO_APP_KEY를 info.plist에서 찍어봐도 잘 나오고, uri도 정상적으로 들어가있습니다.

혹시나 싶어서 RNKakaoLogins.swift에서 init할 때 아래와 같이 로그로 남겨보니

> let appKey: String? = Bundle.main.object(forInfoDictionaryKey: "KAKAO_APP_KEY") as? String
>         NSLog("!!!!!!!!!!!!!!!!!!!!!!KAKAO_APP_KEY!!!!!!!!!!!!!!!!!!!!!!!")
>         NSLog("%s", appKey!)
>         NSLog("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
>         KakaoSDKCommon.initSDK(appKey: appKey!)
>         NSLog("!!!!!!!!!!!!!redirectUri!!!!!!!!!!!!!!!!!!!!!!!")
>         NSLog("%s", KakaoSDKCommon.shared.redirectUri())
>         NSLog("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")

아래와 같이 바이너리??값이 나옵니다. 

> 2021-04-05 21:04:28.092370+0900 TestApp[3830:175438] !!!!!!!!!!!!!!!!!!!!!!KAKAO_APP_KEY!!!!!!!!!!!!!!!!!!!!!!!
> 2021-04-05 21:04:28.093050+0900 TestApp[3830:175438] Ai≥ﬁ°!
> 2021-04-05 21:04:28.093110+0900 TestApp[3830:175438] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 2021-04-05 21:04:28.093252+0900 TestApp[3830:175438] !!!!!!!!!!!!!redirectUri!!!!!!!!!!!!!!!!!!!!!!!
> 2021-04-05 21:04:28.093384+0900 TestApp[3830:175438] (;∂ﬁ
> 2021-04-05 21:04:28.093423+0900 TestApp[3830:175438] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

이것 떄문에 계속 리다이렉트에서 빠지는 것 같은데, 
iOS 시뮬레이터에서는 잘되는데(카톡 앱이 없으니 당연할지도요) 실제 기기에서 해보면 저부분에서 계속 안되고있습니다 ㅠㅠ

어느부분을 고쳐야 잘 돌아갈까요??ㅠㅠ

스위프트고 네이티브고 처음이라서 헤매는 부분이 많네요ㅠ

### Tested environment (Emulator? Real Device?)

iPhone7

**Comment by hyochan** [comment]
`3.0.5`에서도 동일하게 되는지 한번 확인해주시면 감사하겠습니다.

**Comment by iKoru** [comment]
@hyochan 업데이트하니 잘 되네요! 감사합니다 :)
