### ISSUE TITLE
KakaoLoginExample 테스트 에러

### ISSUE THREAD

**Issue by JinleeJeong** [react-native-seoul/react-native-kakao-login#208]
### Version of kakao-login libraries

3.0.6

### Version of react-native

0.64.0

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

KakaoLoginExample 정상 동작

### Tested environment (Emulator? Real Device?)

갤럭시9+

### Actual behavior

```
error: Error: While trying to resolve module `@react-native-seoul/kakao-login` 
from file `/react-native-kakao-login/KakaoLoginExample/src/components/pages/Intro.tsx`, 
the package `/react-native-kakao-login/KakaoLoginExample/node_modules/@react-native-seoul/kakao-login/package.json` was successfully found. 

However, this package itself specifies a `main` module field that could not be resolved 
(`react-native-kakao-login/KakaoLoginExample/node_modules/@react-native-seoul/kakao-login/index.js`.
```

안녕하세요 !!

KakaoLoginExample을 테스트 해보기 위해서, 전체를 클론 받고, 
https://github.com/react-native-seoul/react-native-kakao-login#how-to-run-example-project

예시 따라서 진행을 해봤습니다. 하지만, entry file이 js가 아니라 ts이기 때문에, 빌드는 되지만 해당 에러가 발생합니다.

entry file 확장자를 변경하거나 직접 `@react-native-seoul/kakao-login`를 이용할 때는 가능합니다! 
안내가 필요할 것 같습니다. 확인 부탁드립니다!

**Comment by hyochan** [comment]
root 폴더에서 `yarn && yarn build`를 하신후 Example에서 다시 `yarn`을 해보시면 될듯합니다.
