### ISSUE TITLE
[안드로이드] 카카오가 설치되어 있지 않은 경우 웹브라우저에 의한 로그인이 동작하지 않습니다.

### ISSUE THREAD

**Issue by AMaster124** [react-native-seoul/react-native-kakao-login#209]
### Version of kakao-login libraries

버전 : 3.0.6

### Version of react-native

react-native : 0.63.4
react-native-cli : 2.0.1

### Platforms you faced the error (IOS or Android or both?)

문제가 발생한 플랫홈 : android
### Expected behavior

카카오가 깔려 있지 않는 경우 웹브라우저에 의한 로그인이 동작해야 합니다.

### Actual behavior

겪고 있는 상황 : 카카오 로그인 버튼을 눌러 동의화면이나 계정 입력 브라우저로 화면이 변경 된 후 확인 버튼을 누르면 초기 화면으로 돌아오기는 하는데 아무런 값도 리턴하지 않고 다음 단계로 넘어가지 않습니다.

### Tested environment (Emulator? Real Device?)

가능한 디바이스나 에뮬에서 테스트를 했는데 동작하는것이 없었습니다.

이전에는 버전 2.10.2를 사용하다가 이번에 새 버전으로 업그레이드 하려고 하는데 잘 안되네요
아이폰에서는 정상동작하는데 안드로이드만 안되요.

빠르게 답변 주시면 정말 감사하겠습니다.

**Comment by kasumil** [comment]
공감합니다. 저도 3.0.6이 에뮬레이터 로그인이 안되서 그래들 잘못설정했나하고 엎어야 하나 했네요

**Comment by hyochan** [comment]
재현이 불가능합니다. 카카오톡을 지우고 시도해보았는데 잘 작동하네요.

**Comment by JeffGuKang** [comment]
> ### Version of kakao-login libraries
> 
> 버전 : 3.0.6
> ### Version of react-native
> 
> react-native : 0.63.4
> react-native-cli : 2.0.1
> ### Platforms you faced the error (IOS or Android or both?)
> 
> 문제가 발생한 플랫홈 : android
> ### Expected behavior
> 
> 카카오가 깔려 있지 않는 경우 웹브라우저에 의한 로그인이 동작해야 합니다.
> ### Actual behavior
> 
> 겪고 있는 상황 : 카카오 로그인 버튼을 눌러 동의화면이나 계정 입력 브라우저로 화면이 변경 된 후 확인 버튼을 누르면 초기 화면으로 돌아오기는 하는데 아무런 값도 리턴하지 않고 다음 단계로 넘어가지 않습니다.
> ### Tested environment (Emulator? Real Device?)
> 
> 가능한 디바이스나 에뮬에서 테스트를 했는데 동작하는것이 없었습니다.
> 
> 이전에는 버전 2.10.2를 사용하다가 이번에 새 버전으로 업그레이드 하려고 하는데 잘 안되네요
> 아이폰에서는 정상동작하는데 안드로이드만 안되요.
> 
> 빠르게 답변 주시면 정말 감사하겠습니다.

일반적으로 설정 문제입니다. 안드로이드 관련 설정을 본 레파지토리의 example과 비교해보세요.

**Comment by kasumil** [comment]
원인을 찾았습니다. 
1. android studio - 해당 프로젝트 - android - react-native-kakao-login - kakao_sthings.xml에서 
   저의 네이티브 앱키로 변경하고, (해당 부분을 작업해주지 않으면 개발자 네이티브앱 주소로 넘어갑니다)
2. android - app - src - main - androidManifest.xml에서
"kakao{1231545}" -> "kakao1235465" 이렇게 작성해주면 되는 것이었네요. 1번의 없이 네이티브 앱 키를 {}로 감싸지 않으면 원개발자님의 네이티브 주소로 넘어가는 바람에 {}감싸서 썼는데, 1번 작업해주면 그냥 정상 작동됩니다.

**Comment by hyochan** [comment]
네 비슷한 질문들이 많아서 유트브 영상도 있으니 참고하시면 되겠습니다~
https://www.youtube.com/watch?v=YJaOT3ZVKNg&t=15s
