### ISSUE TITLE
unexpected token';'  no stack 오류발생

### ISSUE THREAD

**Issue by jimanjang** [react-native-seoul/react-native-kakao-login#211]
### Version of kakao-login libraries

3.0.7

### Version of react-native 3.0.7

react-native-cli: 2.0.1
react-native : 0.64

### Platforms you faced the error (IOS or Android or both?)

안드로이드

### Expected behavior

예제파일을 그대로 사용해서 yarn android를 하면 정상적으로 화면이 나와야 하는데 오류가 발생

### Actual behavior

unexpected token';' 
unexpected token';' 
no stack
no stack

### Tested environment (Emulator? Real Device?)

애뮬레이터

**Comment by jimanjang** [comment]
usb로 실제연결을 해도 동일한 문제가 발생합니다 ㅠ.

**Comment by hyochan** [comment]
#208 에 제 코멕트는 확인해보셨나요?

**Comment by jimanjang** [comment]
#208 에 있는 코멘트 대로 root 폴더에서 yarn& yarn build 실행 후 KakaoLoginExample에서 yarn 해봤지만 동작하지 않습니다.

**Comment by hyochan** [comment]
`KakaoLoginExample`에서 다시 설치하실 때는 `rm -rf node_modules && yarn`을 하셨나요?

**Comment by jimanjang** [comment]
아니요 rm 명령어를 쓸 수 없어서 사용하지 않았습니다!

**Comment by leekangrim** [comment]
`package.json` 파일에 `41번째 줄`에 
"translate-fbts": "fbt-translate --jenkins --source-strings  src/utils/i18n/fbt/.source_strings.json --translations src/assets/translations/*.json >  src/utils/i18n/fbt/translatedFbts.json",
에서 *.json을 ko.json으로 바꿔보세요. 그러면 화면을 볼 수 있을 것 입니다.
-ssafy 광주 4기 자율pjt C105 일동-
