### ISSUE TITLE
카카오톡이 설치되어있으나 로그인이 되어있지 않으면 에러가 발생합니다.

### ISSUE THREAD

**Issue by toy0605** [react-native-seoul/react-native-kakao-login#214]
### Version of kakao-login libraries

react-native-kakao-login 3.0.7

### Version of react-native

react 16.13.1
react-native 0.63.4

### Platforms you faced the error (IOS or Android or both?)

Android에서 발생했으나
iOS, Android 둘다 발생할 것으로 예상합니다.

### Expected behavior

카카오톡으로 로그인 시도가 아닌 웹페이지로 카카오 로그인이 나와야합니다.

### Actual behavior

에러가 발생합니다.
```
// AuthError.getReponse() 내용
{
    Error: "NotSupportError",
    Description: "KakaoTalk is installed, but Kakao account is not connected" // (였던것으로 기억합니다.)
}
```

### Tested environment (Emulator? Real Device?)

Galaxy S9+, Galaxy S20

**Comment by hyochan** [comment]
Kakao Dev Talk에서 다른 분이 글을 달아주셔서 봤던 것 같은데요. App 사이드에서 관련 error을 핸들링 하라고 답변이 있었던 걸로 기억됩니다.

카카오톡에 로그인되지 않았습니다. 카카오톡 앱에 로그인 후 시도해주세요 등이요. 물론 sdk가 보완되면 좋겠지만 저희쪽 이슈가 아니니 일단 닫겠습니다.

**Comment by toy0605** [comment]
@hyochan 답글 감사드립니다. react-native 내에서 직접 에러 핸들링하려고 하여도 현재 login() 함수로는 자동적으로 카카오톡으로 로그인을 시도하기 때문에 처리가 어렵습니다.
SDK의 loginWithKakaoTalk()가 아닌 강제로 loginWithKakaoAccount()를 호출 할 수 있는 함수가 있으면 react-native 내에서 핸들링하여 처리 할 수 있을 것 같습니다.
