### ISSUE TITLE
Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want? 

### ISSUE THREAD

**Issue by Wanderlust-sol** [react-native-seoul/react-native-kakao-login#217]
### Version of kakao-login libraries

v3.1.1
### Version of react-native

0.63.3
### Platforms you faced the error (IOS or Android or both?)

Android
### Expected behavior

로그인 창이 정상적으로 열려야합니다.
### Actual behavior
```
Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want? 
```
해당 에러와 함께 로그인 창이 열리지 않습니다. (현재 카카오 웹링크는 열리지만 카카오톡 앱이 설치된 상태에서는 아무 반응이 없네요)
### Tested environment (Emulator? Real Device?)
실제 기기

**Comment by hyochan** [comment]
다른분들은 잘 되는걸로 보아 설정 문제로 의심이 됩니다. 한번 더 확인해주시면 좋을 것 같습니다.

**Comment by qsoo** [comment]
동일 이슈가 발생했는데요. 
정확한 해결 방법은 아직 찾지 못했고 저 같은 경우에는 카카오 로그인 라이브러리를 다운그레이드하니 정상적으로 작동하였습니다.


Version of kakao-login libraries
v3.0.7

Version of react-native
0.64.0

@Wanderlust-sol 
임시방편으로라도 도움이 되길 바라겠습니다!

**Comment by hyochan** [comment]
@qsoo 버전 확인 감사합니다. 확인해보겠습니다~

**Comment by Wanderlust-sol** [comment]
@qsoo 덕분에 임시방편으로 해결했네요! 감사합니다~

**Comment by hyochan** [comment]
`3.3.1` 이후부터 써주시면 됩니다~
