### ISSUE TITLE
unlink method는 개발중이신가요?

### ISSUE THREAD

**Issue by Bang9** [react-native-seoul/react-native-kakao-login#22]
카카오톡 SDK의 연결해제 기능은 개발 예정에 없으신지 궁금합니다.

**Comment by dooboolab** [comment]
어떤 부분을 말씀하시는건지 첨언 부탁드립니다. 저도 카카오 sdk 쓸 일이 별로 없어서요.

**Comment by Bang9** [comment]
카카오 계정과 어플리케이션을 연결해제 하는 기능입니다.
[https://developers.kakao.com/docs/android/user-management#%EC%95%B1-%EC%97%B0%EA%B2%B0-%ED%95%B4%EC%A0%9C](url)

**Comment by dooboolab** [comment]
@Bang9 현재 11월까지 일정이 좀 빠듯한게 있어서 추가 진행이 어렵긴 합니다 ㅜ 그 때 이후에 한번 보겠습니다. 그 전에 `PR`을 주시면 그건 언제든지 신속히 처리하겠습니다.

**Comment by heyman333** [comment]
@Bang9 님 이 API는 작업계획 없으신가요???

**Comment by Bang9** [comment]
> @Bang9 님 이 API는 작업계획 없으신가요???

시간나면 한번 작업해볼게요 🙂
