### ISSUE TITLE
Could not set unknown property 'jvmTarget' for extension 'android'

### ISSUE THREAD

**Issue by themore8109** [react-native-seoul/react-native-kakao-login#220]
### Version of kakao-login libraries

3.2.0

### Version of react-native

0.64.0

### Platforms you faced the error (IOS or Android or both?)

android

### Expected behavior

빌드가 되어야 합니다.

### Actual behavior

아래와 같은 에러가 나며, 빌드에 실패합니다.
<pre>
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/..../node_modules/@react-native-seoul/kakao-login/android/build.gradle' line: 45

* What went wrong:
A problem occurred evaluating project ':react-native-seoul_kakao-login'.
> Could not set unknown property 'jvmTarget' for extension 'android' of type com.android.build.gradle.LibraryExtension.
</pre>

임시방편으로, 아래의 내용을 주석처리후 정상적으로 빌드되는것을 확인 하였습니다.
`/node_modules/@react-native-seoul/kakao-login/android/build.gradle`
45 line
`// jvmTarget = "1.8"`

### Tested environment (Emulator? Real Device?)

빌드 단계의 오류.

**Comment by hyochan** [comment]
`3.3.0`을 다시 시도해주세요~
