### ISSUE TITLE
Error: Calling startActivity() from outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?

### ISSUE THREAD

**Issue by themore8109** [react-native-seoul/react-native-kakao-login#221]
### Version of kakao-login libraries

3.2.0

### Version of react-native

0.64.0

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

Kakao로그인이 되어야 한다.

### Actual behavior

카카오로 리다이렉트도 되지 않고 아래와 같은 오류가 나타나는 것으로 보입니다.
code
`login().then(() => {...}).catch( err => console.log(err) )`
error
`
Error: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
`

### Tested environment (Emulator? Real Device?)

Real Device

**Comment by hyochan** [comment]
코드가 반영이 제대로 안되고 배포되었네요. `3.3.0`을 다시 시도해주시길 바랍니다 🙏
