### ISSUE TITLE
getProfile cast exception 

### ISSUE THREAD

**Issue by stevechoi** [react-native-seoul/react-native-kakao-login#222]
### Version of kakao-login libraries

v2-2.5.0

### Version of react-native

0.63.4

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

프로필을 정상적으로 가져옴

### Actual behavior

cast exception 발생 
(kotlin.unit cannot cast to kotlin.jvm.functions.function2)

### Tested environment (Emulator? Real Device?)

galaxy note 8 

![스크린샷 2021-05-04 오전 7 39 30](https://user-images.githubusercontent.com/4636749/116942098-e2d61c80-acab-11eb-89c9-e4b023108cf9.png)
RNKakaoLoginModule.kt 의 getProfile 메소드 171 line 의 as (User?, Throwable?) -> Unit 를 지우니 해결은 되어서 일단 이렇게 빌드는 했는데, 이슈 확인이 필요합니다.

**Comment by hyochan** [comment]
넵 좋은 수정이네요. 다음부터는 `PR`을 보내주시면 감사하겠습니다.

**Comment by bigeyes0218** [comment]
같은 이슈가 있었습니다. 수정하니 해결되네요. 감사합니다.
