### ISSUE TITLE
xcode 12.5에서 빌드 실패

### ISSUE THREAD

**Issue by GreenCheese-dev** [react-native-seoul/react-native-kakao-login#225]
### Version of kakao-login libraries

    "@react-native-seoul/kakao-login": "^3.0.7",

### Version of react-native

    "react-native": "0.64.1",

### Platforms you faced the error (IOS or Android or both?)

   IOS

### Expected behavior

  빌드

### Actual behavior

   빌드 실패

### Tested environment (Emulator? Real Device?)

    IOS 14.5 simulator

xcode가 12.5로 업데이트되면서 개발에 사용중이던 아이맥의 업데이트(카탈리나 모델 미지원)를 지원하지 않아 디바이스 테스트를 위해 작업중이던 프로젝트를 맥북(빅서, xcode 12.5)에 clone하여 빌드를 시도했습니다.

안드로이드에서는 정상 작동하나, yarn ios시 
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65.
error 메시지를 보여주며 빌드가 되지 않았고 아래의 지침대로 시도하였으나 해결되지 않았습니다.
(https://github.com/facebook/react-native/issues/31480)

새로 프로젝트를 생성하여 빌드할 경우 문제없이 실행되어 dependencies가 의심되었고, 하나 하나 체크하던 도중     "@react-native-seoul/kakao-login": "^3.0.7", 를 제거했을 때 빌드를 성공하였습니다.
제가 작업하던 프로젝트는 올려주신 영상을 참고하여 셋팅하였습니다. 

이 자리를 빌어 유용한 프로젝트 공유에 감사드립니다.

**Comment by hyochan** [comment]
@GreenCheese-dev 빌드 오류가 저거 외에 표시되는게 있을까요? 그리고 혹시 m1을 사용하고 계신지도 궁금합니다.

테스트 프로젝트도 한번 확인해주시고요.

**Comment by GreenCheese-dev** [comment]
@hyochan 안녕하세요.
말씀해주신 대로 테스트 해보았습니다.
현재 테스트한 디바이스 정보는 아래와 같습니다.
MacBook Pro (15-inch, 2017) - intel mac / macOS Big Sur(11.3) / xcode 12.5 / 

KakaoLoginExample 코드에서 테스트하니 제가 작업중이 프로젝트와 동일한 오류가 발생했습니다. (android - 빌드 성공 / ios - 빌드 실패)
에러는 예제 소스에서 나온 에러 중 일부를 발췌하여 올려드립니다.

----------------------------------------------------------------------------------

$ npx react-native run-ios
info Found Xcode workspace "KakaoLoginExample.xcworkspace"
info Building (using "xcodebuild -workspace KakaoLoginExample.xcworkspace -configuration Debug -scheme KakaoLoginExample -destination id=C14B1D2A-5E42-4F89-B13C-263B8DDBE6CC")
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening KakaoLoginExample.xcworkspace.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace KakaoLoginExample.xcworkspace -configuration Debug -scheme KakaoLoginExample -destination id=C14B1D2A-5E42-4F89-B13C-263B8DDBE6CC

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

note: Using new build system
note: Building targets in parallel
note: Planning build
note: Analyzing workspace
note: Constructing build description
note: Build preparation complete
CompileC /Users/byrmacbook/Library/Developer/Xcode/DerivedData/KakaoLoginExample-bsuprvijimhpkscwvrwcumzsefet/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-cxxreact.build/Objects-normal/x86_64/NativeToJsBridge.o /Users/byrmacbook/Desktop/rn/pjt3/TestProject/react-native-kakao-login/KakaoLoginExample/node_modules/react-native/ReactCommon/cxxreact/NativeToJsBridge.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'React-cxxreact' from project 'Pods')


********** 중략 ****************


2021-05-06 17:47:39.626 xcodebuild[49240:716425]  DTDeviceKit: Failed to mount DDI from '<DVTFilePath:0x7fe8c9577500:'/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/DeviceSupport/7.4/DeveloperDiskImage.dmg'>', error=-402652958: Error Domain=com.apple.dtdevicekit Code=806 "Failed to prepare device for development." UserInfo={AssociatedMobileDeviceFunction=AMDeviceMountImage, NSUnderlyingError=0x7fe8c84160c0 {Error Domain=com.apple.dt.MobileDeviceErrorDomain Code=-402652958 "The device is locked." UserInfo={MobileDeviceErrorCode=(0xE80000E2), com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x000000011258d3b8 DTDKCreateNSErrorFromAMDErrorCode + 220
	1   DTDeviceKitBase                     0x00000001125c9674 -[DTDKMobileDeviceToken _mountDeveloperDiskImage:withError:] + 1024
	2   DTDeviceKitBase                     0x00000001125ca08b __58-[DTDKMobileDeviceToken mountDeveloperDiskImageWithError:]_block_invoke + 609
	3   libdispatch.dylib                   0x00007fff203fd7e6 _dispatch_client_callout + 8
	4   libdispatch.dylib                   0x00007fff2040a5ae _dispatch_lane_barrier_sync_invoke_and_complete + 60
	5   DTDeviceKitBase                     0x00000001125c9dca -[DTDKMobileDeviceToken mountDeveloperDiskImageWithError:] + 185
	6   IDEiOSSupportCore                   0x0000000111c344b4 __43-[DVTiOSDevice prepareProxiedDevicesAsync:]_block_invoke + 554
	7   DVTFoundation                       0x000000010418b931 __DVT_CALLING_CLIENT_BLOCK__ + 7
	8   DVTFoundation                       0x000000010418d55b __DVTDispatchAsync_block_invoke + 1191
	9   libdispatch.dylib                   0x00007fff203fc603 _dispatch_call_block_and_release + 12
	10  libdispatch.dylib                   0x00007fff203fd7e6 _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x00007fff204035ca _dispatch_lane_serial_drain + 606
	12  libdispatch.dylib                   0x00007fff2040408d _dispatch_lane_invoke + 366
	13  libdispatch.dylib                   0x00007fff2040dbed _dispatch_workloop_worker_thread + 811
	14  libsystem_pthread.dylib             0x00007fff205a44c0 _pthread_wqthread + 314
	15  libsystem_pthread.dylib             0x00007fff205a3493 start_wqthread + 15
), DVTRadarComponentKey=261622, NSLocalizedDescription=The device is locked.}}, NSLocalizedRecoverySuggestion=If you are certain that Xcode supports development on this device, try disconnecting and reconnecting the device., NSLocalizedFailure=This operation can fail if the version of the OS on the device is newer than the version of Xcode that is running., DVTRadarComponentKey=487927, NSLocalizedDescription=Failed to prepare device for development.}
2021-05-06 17:47:43.859 xcodebuild[49240:716425]  DTDeviceKit: Failed to mount DDI from '<DVTFilePath:0x7fe8c9577500:'/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/DeviceSupport/7.4/DeveloperDiskImage.dmg'>', error=-402652958: Error Domain=com.apple.dtdevicekit Code=806 "Failed to prepare device for development." UserInfo={AssociatedMobileDeviceFunction=AMDeviceMountImage, NSUnderlyingError=0x7fe8c7eb3fd0 {Error Domain=com.apple.dt.MobileDeviceErrorDomain Code=-402652958 "The device is locked." UserInfo={MobileDeviceErrorCode=(0xE80000E2), com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x000000011258d3b8 DTDKCreateNSErrorFromAMDErrorCode + 220
	1   DTDeviceKitBase                     0x00000001125c9674 -[DTDKMobileDeviceToken _mountDeveloperDiskImage:withError:] + 1024
	2   DTDeviceKitBase                     0x00000001125ca08b __58-[DTDKMobileDeviceToken mountDeveloperDiskImageWithError:]_block_invoke + 609
	3   libdispatch.dylib                   0x00007fff203fd7e6 _dispatch_client_callout + 8
	4   libdispatch.dylib                   0x00007fff2040a5ae _dispatch_lane_barrier_sync_invoke_and_complete + 60
	5   DTDeviceKitBase                     0x00000001125c9dca -[DTDKMobileDeviceToken mountDeveloperDiskImageWithError:] + 185
	6   IDEiOSSupportCore                   0x0000000111c344b4 __43-[DVTiOSDevice prepareProxiedDevicesAsync:]_block_invoke + 554
	7   DVTFoundation                       0x000000010418b931 __DVT_CALLING_CLIENT_BLOCK__ + 7
	8   DVTFoundation                       0x000000010418d55b __DVTDispatchAsync_block_invoke + 1191
	9   libdispatch.dylib                   0x00007fff203fc603 _dispatch_call_block_and_release + 12
	10  libdispatch.dylib                   0x00007fff203fd7e6 _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x00007fff204035ca _dispatch_lane_serial_drain + 606
	12  libdispatch.dylib                   0x00007fff2040408d _dispatch_lane_invoke + 366
	13  libdispatch.dylib                   0x00007fff2040dbed _dispatch_workloop_worker_thread + 811
	14  libsystem_pthread.dylib             0x00007fff205a44c0 _pthread_wqthread + 314
	15  libsystem_pthread.dylib             0x00007fff205a3493 start_wqthread + 15
), DVTRadarComponentKey=261622, NSLocalizedDescription=The device is locked.}}, NSLocalizedRecoverySuggestion=If you are certain that Xcode supports development on this device, try disconnecting and reconnecting the device., NSLocalizedFailure=This operation can fail if the version of the OS on the device is newer than the version of Xcode that is running., DVTRadarComponentKey=487927, NSLocalizedDescription=Failed to prepare device for development.}
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/byrmacbook/Library/Developer/Xcode/DerivedData/KakaoLoginExample-bsuprvijimhpkscwvrwcumzsefet/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Flipper-Folly.build/Objects-normal/x86_64/DistributedMutex.o /Users/byrmacbook/Desktop/rn/pjt3/TestProject/react-native-kakao-login/KakaoLoginExample/ios/Pods/Flipper-Folly/folly/synchronization/DistributedMutex.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

info Run CLI with --verbose flag for more details.

----------------------------------------------------------------------------------





아래는 xcode 상에서 나타나는 에러 메시지 입니다.
----------------------------------------------------------------------------
Undefined symbols for architecture x86_64:
  "Swift._ArrayBuffer._copyContents(initializing: Swift.UnsafeMutableBufferPointer<A>) -> (Swift.IndexingIterator<Swift._ArrayBuffer<A>>, Swift.Int)", referenced from:
      generic specialization <serialized, Swift._ArrayBuffer<Swift.Int8>> of Swift._copyCollectionToContiguousArray<A where A: Swift.Collection>(A) -> Swift.ContiguousArray<A.Element> in libAlamofire.a(NetworkReachabilityManager.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

❌  Undefined symbol: Swift._ArrayBuffer._copyContents(initializing: Swift.UnsafeMutableBufferPointer<A>) -> (Swift.IndexingIterator<Swift._ArrayBuffer<A>>, Swift.Int)
-----------------------------------------------------------------------------

도움에 정말 감사드립니다. 건강하시고 하루 편히 마무리세요!!

**Comment by deokchanjung** [comment]
저도 최근 iOS 14.5가 업데이트 되면서, XCode도 12.5로 업데이트 했는데요. 그동안 빌드가 잘 되던게 업데이트 이후 동일한 현상이 발생하네요.

**Comment by themore8109** [comment]
아래의 내용 참고해 보세요.
https://github.com/react-native-seoul/react-native-kakao-login/issues/218#issuecomment-830981092

**Comment by deokchanjung** [comment]
@themore8109님 감사합니다:) 알려주신대로 했더니 빌드가 잘 되네요!

> 아래의 내용 참고해 보세요.
> [#218 (comment)](https://github.com/react-native-seoul/react-native-kakao-login/issues/218#issuecomment-830981092)

**Comment by hyochan** [comment]
해당 모듈과 관련 없는 이슈로 닫겠습니다.
