### ISSUE TITLE
현재 빌드가 되지 않고 있습니다.

### ISSUE THREAD

**Issue by TheGreatSong** [react-native-seoul/react-native-kakao-login#230]
### Version of kakao-login libraries

"@react-native-seoul/kakao-login": "^3.3.2",

### Version of react-native

"react-native": "0.64.0",

### Platforms you faced the error (IOS or Android or both?)

iOS

### Expected behavior

빌드

### Actual behavior

Undefined symbols for architecture x86_64:
  "Swift._ArrayBuffer._copyContents(initializing: Swift.UnsafeMutableBufferPointer<A>) -> (Swift.IndexingIterator<Swift._ArrayBuffer<A>>, Swift.Int)", referenced from:
      generic specialization <serialized, Swift._ArrayBuffer<Swift.Int8>> of Swift._copyCollectionToContiguousArray<A where A: Swift.Collection>(A) -> Swift.ContiguousArray<A.Element> in libAlamofire.a(NetworkReachabilityManager.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Swift._ArrayBuffer._copyContents(initializing: Swift.UnsafeMutableBufferPointer<A>) -> (Swift.IndexingIterator<Swift._ArrayBuffer<A>>, Swift.Int**
빌드에 실패하고 있으며 해당 메시지가 뜹니다.

### Tested environment (Emulator? Real Device?)
에뮬레이터 : 아이폰 12, iOS 14.5

**Comment by TheGreatSong** [comment]
다음 조언에 따라 빌드를 성공 하였습니다. 그런데 이게 제대로 된 조치인지는 잘 모르겠습니다.
https://github.com/facebook/react-native/issues/31179#issuecomment-829568297

**Comment by redvelvet-fan** [comment]
https://github.com/meedan/react-native-share-menu/issues/123#issuecomment-829921056

저도 위 조언에 따라 하려했는데 아예  iOS쪽 지식이 없어서 그런지 성공하지 못했습니다. ㅠㅠ

그래서 @TheGreatSong 님이 링크 걸어주신대로 해서 빌드가 되긴했습니다만 
저 또한 뭔가 있는걸 지워서 해결한거라 뭔가 찝찝하네요.. Facebook쪽에서 해결되길 기다리는 수 밖에 없을거 같아요

에뮬레이터 : 아이폰 12 , iOS 14.5
Xcode : Version 12.5 (12E262)
React-Native : 0.64.1

ex) 여러 글을 읽어보니 Xcode 12.5 에서 발생하는 버그 같습니다 ...

**Comment by hyochan** [comment]
해당 모듈과 관련 없는 이슈로 닫겠습니다.
