### ISSUE TITLE
npx pod-install ios 에러 나는 문제 확인해주세요

### ISSUE THREAD

**Issue by kwangheum** [react-native-seoul/react-native-kakao-login#232]
### Version of kakao-login libraries

3.3.2

### Version of react-native

0.64.1

### Platforms you faced the error (IOS or Android or both?)

IOS

### Actual behavior

문서 보며 하고있는데 안됩니다... 일단 설정 하라는데로 다 하긴 했습니다.

_[!] CocoaPods could not find compatible versions for pod "kakao-login":
  In Podfile:
    kakao-login (from `../node_modules/@react-native-seoul/kakao-login`)

Specs satisfying the `kakao-login (from `../node_modules/@react-native-seoul/kakao-login`)` dependency were found, but they required a higher minimum deployment target._

npx pod-install ios 로 하면 해당 에러 납니다.

이거 때문인지 

_TypeError: null is not an object (evaluating 'RNKakaoLogins.getProfile')_

이렇게 뜨네요..

### Tested environment (Emulator? Real Device?)

ios 시뮬레이터 아이폰 12

**Comment by hyochan** [comment]
ios platform target을 11이상으로 맞춰줘보실래요?

**Comment by kwangheum** [comment]
> ios platform target을 11이상으로 맞춰줘보실래요?

맞춰도 동일 합니다 확인해보니 xcode에서 AppDelegate.m 에서 RNKakaoLogins.h 를 못찾네요..?
현재 xcode에서 작업한것은 아래와 같아요.
1.  swiftbridge 헤더 파일 생성
2. info.plist에 readme 보면서 내용 넣기
3. ios platform target 11
4. AppDelegate.m에 readme에 있는 내용 추가
5. 카카오 개발자 홈페이지에서 로그인 활성화
6. bundle identifier 를 카카오 개발자 홈페이지에 있는 것으로 변경

 혹시 추가로 해야하는게 있나요?

**Comment by hyochan** [comment]
`rm -rf node_modules && yarn` 을 해서 새로 설치한다음 해보시거나 그래도 안된다면 `3.3.0` 도 설치해보시고 결과를 알려주실 수 있을까요.
