### ISSUE TITLE
expo 지원은 안하는 겁니까?

### ISSUE THREAD

**Issue by 100milliongold** [react-native-seoul/react-native-kakao-login#234]
### Version of kakao-login libraries

v2.10.0

### Version of react-native

0.64.2

### Platforms you faced the error (IOS or Android or both?)

login

### Expected behavior

login

### Actual behavior

expo 사용중인데 react-native-kakao-login 을 설치후에 사용할려고 해도 잘안됩니다.

### Tested environment (Emulator? Real Device?)

안드로이드, ios

**Comment by Bang9** [comment]
Expo 프로젝트에서, 자바스크립트가 아닌 네이티브(android, ios) 코드가 포함된 외부 라이브러리를 사용하시려면
프로젝트를 Eject 하셔야 진행하실 수 있습니다.

https://docs.expo.io/bare/exploring-bare-workflow/

**Comment by hi-paul** [comment]
expo프로젝트에서 native모듈 지원은 이 분들이 해주시는게 아니라 expo 팀에서 지원해주셔야 사용가능해요.
근데 현재는 별 상관없는게 expo의 태생적 한계같은 부분을 EAS build라는 서비스를 내놓아서 그걸로 빌드하시면 그런 제한없이 native 모듈을 빌드하실수 있어요.
EAS build가 프리뷰 단계지만, 사용해본 결과 운영에서도 사용해볼 만합니다.
