### ISSUE TITLE
안드로이드에서 빌드가 되지 않는 이슈

### ISSUE THREAD

**Issue by lazyflog** [react-native-seoul/react-native-kakao-login#237]
### Version of kakao-login libraries

3.3.2

### Version of react-native

0.64.2

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

빌드

### Actual behavior

<img width="862" alt="image" src="https://user-images.githubusercontent.com/49199496/124071036-bd7e4880-da79-11eb-92f4-edd94ffb5de8.png">
와 같이 Manifest merger failed with multiple errors, see logs 오류가 뜨면서 빌드가 되지 않습니다.
정작 로그를 보면 별 내용도 없습니다.

### Tested environment (Emulator? Real Device?)

에뮬레이터: Pixel_3a
실제기기: 갤럭시 s6

**Comment by ruebark** [comment]
AndroidManifest.xml 파일에서 오류가 있는 것 같습니다. 
해당 파일 한번 확인해보세요.

**Comment by lazyflog** [comment]
전 아무리 찾아봐도 제가 뭘 잘못 적어줬는지 모르겠습니다.ㅠㅠ
<img width="901" alt="image" src="https://user-images.githubusercontent.com/49199496/124075695-3f717000-da80-11eb-96b1-214712e89e8c.png">

**Comment by ruebark** [comment]
gradle 버전 문제일 수 도 있다고 합니다.

https://devtalk.kakao.com/t/react-native-execution-failed-for-task-app-processdebugmanifest/112101

https://stackoverflow.com/questions/67240343/build-failed-missing-package-key-attribute
https://ddolcat.tistory.com/870

**Comment by lazyflog** [comment]
grade 버전을 최신버전으로 업데이트 하니까 잘 작동하네요! 감사합니다!!
