### ISSUE TITLE
안드로이드 코틀린 빌드에러 with react-navigation

### ISSUE THREAD

**Issue by Eumhongin** [react-native-seoul/react-native-kakao-login#263]
### Version of kakao-login libraries

"@react-native-seoul/kakao-login": "^3.3.3",

### Version of react-native

"react": "17.0.2",
"react-native": "0.66.1",

### Platforms you faced the error (IOS or Android or both?)

안드로이드

### Expected behavior

안드로이드 빌드가 되어야함

### Actual behavior

라이브러리 설치후, 카카오 디벨로퍼스에서 프로젝트를 만들고 키해시를 등록함.
Post Installation을 모두 진행하였으나 
<img width="727" alt="스크린샷 2021-10-29 오후 9 41 07" src="https://user-images.githubusercontent.com/23710025/139436115-c5bcd8a8-87af-4895-8d63-190da48d5419.png">
해당 오류가 발생하여 #256 를 참조하여 1.3.50 으로 변경(build.gradle 세팅은 예제와 완전 똑같이 시작함)

현재 react-navigation 을 사용하고 있고 기본적으로 받아야하는 react-native-screen 에서 코틀린 빌드에러가 발생.

### Tested environment (Emulator? Real Device?)

API 29 안드로이드 에뮬레이터

**Comment by lets-gojae** [comment]
```
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        ndkVersion = "21.4.7075529"
        kotlinVersion = '1.5.0'
    }
```
kotlinVersion 1.5.0으로 변경하시면 됩니다.

**Comment by hyochan** [comment]
@lets-gojae 감사합니다. 메일을 보다가 중요한 이슈 같아서 확인하고 `3.4.0`으로 배포했습니다.
