### ISSUE TITLE
안드로이드 카카오톡 배포버전에서 튕기는 문제 발생

### ISSUE THREAD

**Issue by Stackerr** [react-native-seoul/react-native-kakao-login#266]
### Version of kakao-login libraries

3.3.3

### Version of react-native

0.64.1

### Platforms you faced the error (IOS or Android or both?)

android 
### Expected behavior

카카오톡 정상 로그인
### Actual behavior

개발 버전까지는 정상적으로 로그인이 되었으나, 배포버전에서는 카카오톡 로그인 버튼을 누르면 잠시 뒤에 앱이 꺼집니다. 
구글 로그인 관련해서도 sha1 업로드키를 카카오톡 developer hash key 에 입력했으나, 동일한 문제가 발생합니다.
### Tested environment (Emulator? Real Device?)

android 전체

**Comment by Stackerr** [comment]
해당 문제 해소되어서 자답합니다. 
-keep class com.kakao.sdk.**.model.* { <fields>; } 이부분을 proguard-rules.pro 여기에 추가해주시면 됩니다.
기존에 close 되어 있어서 찾기 어려우실꺼라 다시 한번 결과 남깁니다

**Comment by juzero** [comment]
이거때문에 며칠 고생했는데 감사합니다.
