### ISSUE TITLE
카카오 라이브러리 세팅하기 질문입니다.

### ISSUE THREAD

**Issue by Eumhongin** [react-native-seoul/react-native-kakao-login#277]
안녕하세요 카카오 라이브러리 설치관련해서 질문이있습니다!

카카오 공식홈페이지에서는 .framework를 다운받은뒤 ios프로젝트로 삽입하도록 하고있습니다.

해당부분도 진행해야하나요?

**Comment by hyochan** [comment]
해당 라이브러리에 이미 내재되어 있어서 불필요한 절차입니다.
