### ISSUE TITLE
iOS 카카오톡 앱 로그인 불가 현상

### ISSUE THREAD

**Issue by swkang0513** [react-native-seoul/react-native-kakao-login#286]
### Version of kakao-login libraries

3.4.3

### Version of react-native

0.65.2

### Platforms you faced the error (IOS or Android or both?)

iOS

### Expected behavior

로그인 성공

### Actual behavior

iOS 15.2.0 이후 버전의 실제 아이폰에서 카카오톡 앱을 통한 카카오 로그인 시 다시 앱으로 돌아오지 않고 카카오톡 앱에 머무르는 현상이 발생합니다.
왼쪽 상단의 앱으로 돌아가기를 눌러도 로그인이 되지 않습니다.

### Tested environment (Emulator? Real Device?)

실제 기기
15.0.2: 이상현상 없음
15.2.0: 이상
15.2.1: 이상
15.3.0: 이상

* Info.plist의 URL Scheme 등록이 풀려있어서 생긴 문제였습니다.

**Comment by andrei0807** [comment]
@swkang0513 저도 같은 오류가 발생하는데 문제를 해결하셨는가요?
