### ISSUE TITLE
[IOS]로그인은 정상작동하지만 getProfile() 호출시, 앱 종료 현상 질문드립니다

### ISSUE THREAD

**Issue by ShinHyunJong** [react-native-seoul/react-native-kakao-login#289]
### Version of kakao-login libraries

3.4.3

### Version of react-native

0.64.0

### Platforms you faced the error (IOS or Android or both?)

IOS

### Expected behavior

getProfile 했을 때, 정보 조회 기능 입니다

### Actual behavior
로그인 (login() )은 정상 작동하나 getProfile()이 정상작동하지 않습니다. 에러는 다음과 같습니다
![스크린샷 2022-02-20 오후 6 48 52](https://user-images.githubusercontent.com/22339020/154837163-8bf2f4ed-3b19-4f9e-ac5d-a4001d269fbc.png)

### Tested environment (Emulator? Real Device?)

Iphone 12, iOS 15.3.1 입니다

**Comment by YangJonghun** [comment]
@ShinHyunJong 
에러가 발생한 해당 코드를 아래와 같이 바꾸시고 patch 적용해서 사용해보시면 될 것 같아요
`"id": (user?.id ?? nil) as Any,`

**Comment by hyochan** [comment]
`4.0.0`에서 해결 된 것 같은데 문제가 있으면 다시 알려주세요~!
