### ISSUE TITLE
로그인 시 앱으로 이동하지 않고 웹으로 이동합니다.

### ISSUE THREAD

**Issue by youngyounkim** [react-native-seoul/react-native-kakao-login#290]
### Version of kakao-login libraries

3.4.2

### Version of react-native

0.65.1

### Platforms you faced the error (IOS or Android or both?)

안드로이드 ios 둘다

### Expected behavior

카카오 앱이 있을 경우 웹이 아닌 앱으로 이동시키고 싶습니다.

### Actual behavior

로그인 시 앱으로 이동하지 않고 웹으로 이동합니다.

### Tested environment (Emulator? Real Device?)

앱, 시뮬레이터 둘 다

**Comment by youngyounkim** [comment]
원래 제공되지 않는 기능인가요? 아니면 설정 문제인가요?
제가 잘못한건지 여부만이라도 알려주시면 감사하겠습니다..ㅜ

**Comment by hyochan** [comment]
안녕하세요 답변이 늦었네요~! `4.0.0`을 사용해보시고 알려주시면 좋을 것 같아요.
