### ISSUE TITLE
4.0.0 코틀린 버젼 이슈

### ISSUE THREAD

**Issue by gkqkehs7** [react-native-seoul/react-native-kakao-login#304]
안녕하세요 

 "@react-native-seoul/kakao-login": "^4.0.0" 이용하고 있습니다.

코틀린 버젼이 맞지 않다구 나오는데 4.0.0부터는 kotlinVersion = '1.5.10' 이렇게 해야 작동하는 것 같습니다!

혹시나 안되시는 분들을 위해..

**Comment by hyochan** [comment]
`4.1.0`에서 해결 되었습니다.
