### ISSUE TITLE
property_keys 관련 질문

### ISSUE THREAD

**Issue by nealchoi93** [react-native-seoul/react-native-kakao-login#31]
age_range,
birthday,
gender 등 추가적인 프로퍼티는 가져오지못하는건가요?

**Comment by hyochan** [comment]
제가 과거에 `readme`에 제공한 property외에는 받아오는 방법을 찾지 못하여 제공이 되지 않았습니다. 혹시, `PR`을 주시면 반영하겠습니다.

**Comment by heyman333** [comment]
#98 과 함께 작업 진행하겠습니다.
