### ISSUE TITLE
[ERROR] RN_Android)Login : web parameters are not provided

### ISSUE THREAD

**Issue by LEEJAEHYUB** [react-native-seoul/react-native-kakao-login#324]
### Version of kakao-login libraries
"@react-native-seoul/kakao-login": "^5.0.1",

### Version of react-native
"react-native": "0.69.4",

### Platforms you faced the error (IOS or Android or both?)

android

### Expected behavior

카카오 로그인 함수 실행 시 웹 or 앱으로 연결되어야 함

### Actual behavior

 [Error: Web parameters are not provided] 에러를 뱉습니다.

### Tested environment (Emulator? Real Device?)

android emulator, galaxy s10

현재 에뮬레이터 및 실제 디바이스 둘다 테스트 하고 있습니다.
현재까지의 진행과정은
1. 키 해시 등록 (kakao developer) 완료
2. 라이브러리 설치
3. `AndroidMenifext.xml` activity 등록
```
<activity
      android:name="com.kakao.sdk.auth.AuthCodeHandlerActivity"
      android:exported="true">
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <!-- Redirect URI: "kakao{NATIVE_APP_KEY}://oauth“ -->
        <data android:host="oauth" android:scheme="kakao[NATIVE_APP_KEY]" />
      </intent-filter>
    </activity>
```
4. `android/build.gradle` 에서 코틀린 추가
5. 에뮬레이터 및 실제 디바이스 빌드 성공
6. 코드 작성 중...
```
import { login } from "@react-native-seoul/kakao-login";

  const loginKakao = async () => {
    try {
      let token = await login();
      setKakaoTest("SUCCESS : " + token.toString());
    } catch (error) {
      console.log("ERROR : ", error);
      setKakaoTest("ERROR : " + error.toString());
    }
  };
```

해당 코드를 실행하면 
`ERROR :  [Error: Web parameters are not provided]`
계속 이 에러를 발생시키고 있습니다.
어떤 문제일까요..
답변주시면 감사하겠습니다 !

**Comment by hyochan** [comment]
새로운 버전에서 문제가 발생하는 것 같습니다.
해결되기 전까지 이전 버전을 사용해주시면 좋을 것 같습니다.

[4.2.3](https://github.com/react-native-seoul/react-native-kakao-login/releases/tag/4.2.3)

**Comment by LEEJAEHYUB** [comment]
@hyochan 버전 다운그레이드 후 문제 해결 되었습니다.
