### ISSUE TITLE
login함수 리턴타입 처리의 수정이 필요해보입니다

### ISSUE THREAD

**Issue by YangJonghun** [react-native-seoul/react-native-kakao-login#337]
### Version of kakao-login libraries
v5.2.2

### Version of react-native
RN버전과 관계 없음

### Platforms you faced the error (IOS or Android or both?)
TS문제라 플랫폼과는 무관합니다

### Expected behavior
login함수의 리턴타입이 통일되거나 웹의 login과 분리해야할것같습니다

### Actual behavior
`const { accessToken } = (await KakaoLogins.login()) as KakaoLogins.KakaoOAuthToken`
앱에서 accessToken을 가져오는 경우 타입캐스팅을 강제해야하는 문제

웹 로그인기능이 추가되면서 login함수의 리턴타입이
`Promise<KakaoLogins.KakaoOAuthToken>`
에서
`Promise<KakaoLogins.KakaoOAuthToken | KakaoLogins.KakaoOAuthWebToken>`
로 변경되었는데 스키마가 완전히 달라서 간단한 구조분해할당 지원도 되지 않아 이건 앱/웹 로그인 함수를 분리하거나 스키마를 통일하거나하는 방향으로 수정할 필요가 있을 것 같습니다

**Comment by jaeseong-nuvi-labs** [comment]
getKakaoProfile()도 마찬가지의 문제가 발생하는것 같습니다.

**Comment by bang9** [comment]
#345 의 변경사항을 적용해서 테스트해보실 수 있을까요?

**Comment by YangJonghun** [comment]
@bang9
작성해주신 PR #345 의 리뷰로 남기겠습니다!
