### ISSUE TITLE
login() 호출 시 카카오톡 앱으로 딥링크 되지 않습니다.

### ISSUE THREAD

**Issue by Aningaaq** [react-native-seoul/react-native-kakao-login#339]
### Version of kakao-login libraries

5.2.2

### Version of react-native

0.64.1

### Platforms you faced the error (IOS or Android or both?)

iOS (안드로이드는 테스트해보지 못했습니다)

### Expected behavior

login() api 를 콜하면 카카오톡이 다운로드 되어 있는 ios 기기에서는 카카오톡으로 딥링크 되어야 합니다

### Actual behavior

카카오톡이 깔려있는 기기임에도 딥링크 되지 않고 web ui 가 열리면서 카카오계정으로 로그인하게 됩니다.

### Tested environment (Emulator? Real Device?)

실제 기기 ios 16.0.2 입니다.

**Comment by huynhhq** [comment]
same issue here

**Comment by mym0404** [comment]
[설치 가이드](https://github.com/react-native-seoul/react-native-kakao-login#ios)대로 제대로 설정이 되어있는지 확인하셔야 할 것입니다.

XCode의 로그도 한번 확인해보세요.

외부 앱으로 갈수 없는 경우 Launch Scheme가 제대로 설정되지 않았을 가능성이 큽니다.

**Comment by Aningaaq** [comment]
죄송합니다 제가 LSApplicationQueriesSchemes 를 빼먹었네요. close 하겠습니다.
```<key>LSApplicationQueriesSchemes</key>
+ <array>
+   <string>kakaokompassauth</string>
+   <string>storykompassauth</string>
+   <string>kakaolink</string>
+ </array>
```
