### ISSUE TITLE
카카오 SDK 2.11.1에서 안드로이드 login 콜백이 오지 않는 버그가 있는데, 2.11.2로 올리는건 어떤가요?

### ISSUE THREAD

**Issue by skarl86** [react-native-seoul/react-native-kakao-login#340]
### Version of kakao-login libraries

5.2.0

### Version of react-native

0.65.0

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

login() 호출 후 콜백이 정상적으로 와야함

### Actual behavior

login() 호출 후 콜백이 오지 않는 문제

### Tested environment (Emulator? Real Device?)

갤럭시 S8 안드로이드9 카카오톡 미설치 기기

안드로이드에서 login() 호출 후 콜백이 안되는 문제가 있어서 카카오 개발 포럼에서 찾아보니 [2.11.1에서 버그](https://devtalk.kakao.com/t/loginwithkakaoaccount-callback/125199/10)가 있었던 것 같습니다.

그래서 확인해보니 현재 RN 카카오 로그인 5.2.0에서 사용중인 카카오 SDK 버전이 2.11.1인걸 확인하고 임시로 2.11.2로 올려서 확인해보니 정상적으로 동작하네요.

**Comment by hyochan** [comment]
@skarl86 안녕하세요~! 확인 감사드립니다.
혹시 관련하여 `PR`을 날려주실 수 있으실까요?

**Comment by daheeahn** [comment]
저도 안드로이드 카카오톡 미설치 기기에서 로그인 콜백이 오지 않는 버그가 동일하게 발생되어서, 라이브러리 업데이트 기다리고 있겠습니다! 😃

**Comment by daheeahn** [comment]
자답합니다. 저같은 경우에는 https://github.com/react-native-seoul/react-native-kakao-login#android 2번 Redirect URI 설정에서
`android:exported="true"` 부분을 빼먹어 콜백이 오지 않는 것이었습니다!
