### ISSUE TITLE
네이티브 로그인시 동작하지 않는 현상

### ISSUE THREAD

**Issue by tedkimzikto** [react-native-seoul/react-native-kakao-login#35]
같은 문제가 발생하는데, 다른 분들 괜찮으신가요?

`CANCELED_OPERATION: App restarted during Kakao login procedure. Restarting from the start.`

첫 시도시, 화면 순간 깜빡거리고 위에러 이후에는 반응이 없습니다.  웹으로 로그인을 시도하여 성공하면, 이후 네이티브에서는 성공합니다.

_Originally posted by @tedkimzikto in https://github.com/react-native-seoul/react-native-kakao-logins/issues/9#issuecomment-466990014_

**Comment by heyman333** [comment]
@tedkimzikto 최신 버전으로 다시 설치 해보시고 문제가 있으면 다시 이슈 열어 주시기 바랍니다~
감사합니다.
