### ISSUE TITLE
카카오 로그인 선택 팝업에서 배경 혹은 닫기 버튼을 누를 때 콜백 함수 호출이 안되는 증상

### ISSUE THREAD

**Issue by parksunq** [react-native-seoul/react-native-kakao-login#39]
안드로이드에서 확인한 것 인데요. (iOS는 기기가 없어서 정확한 동작은 모르겠네요.)
복수 타입 선택이 가능한 경우 팝업을 띄워주고 있는데요. 이 때 나가기 버튼을 누르거나 배경을 눌러서 팝업을 닫으면 콜백 함수 호출 없이 팝업만 닫히고 있습니다.
로그인 요청을 하고 콜백을 받아서 처리를 하는데 콜백 전달이 되지 않아 처리를 못하고 있는데요.
사용자가 팝업을 닫는 경우에는 에러 콜백 전달이 가능할까요?

**Comment by heyman333** [comment]
최신버전에서 확인 가능합니다!
