### ISSUE TITLE
카카오 간편로그인

### ISSUE THREAD

**Issue by hckcksrl** [react-native-seoul/react-native-kakao-login#48]
예시대로 카카오 로그인을 하는데

카카오톡이 깔려있는데도 간편로그인은 안되고

다른계정으로 로그인만 뜨는데 원래 이런건가요

아래에 있는 이슈보면 간편로그인창이 뜨는거 같긴한데 혹시 저만이런건가요 

ios입니다

**Comment by rarira** [comment]
@hckcksrl 
https://developers.kakao.com/docs/ios/getting-started#%EA%B0%9C%EB%B0%9C%ED%99%98%EA%B2%BD-%EA%B5%AC%EC%84%B1
페이지의
화이트리스트 추가 설정 하셨는지 확인해 보셔요.

documentation 이 아쉽네요

**Comment by heyman333** [comment]
@hckcksrl 최신버전에 맞춰서 문서를 새롭게 업데이트 했습니다. 그래도 원하는 기능이 동작하지 않는다면 다시 이슈 열어주시기 바랍니다~
