### ISSUE TITLE
post installation 가이드까지 진행한뒤에 build를 해보면 사진과 같은 에러가 발생합니다.

### ISSUE THREAD

**Issue by newKeating** [react-native-seoul/react-native-kakao-login#73]
<img width="730" alt="Screen Shot 2019-10-17 at 11 35 06 AM" src="https://user-images.githubusercontent.com/28520573/66973223-43a20200-f0d2-11e9-9a17-f9bcbee716af.png">

post installation 가이드까지 진행한뒤에 build를 해보면 사진과 같은 에러가 발생합니다.

**Comment by heyman333** [comment]
혹시 현재 쓰고 있는 RN 버전과 설치한 라이브러리 버전을 알 수 있을까요?

**Comment by heyman333** [comment]
@newKeating 
번거로우시겠지만 이슈템플릿을 새로 생성 했으니 이슈를 다시 생성 해주시면 감사하겠습니다~

**Comment by kojongDev** [comment]
안녕하세요. 
저도 방금 이 오류로 찾아보다가, 혹시 해서 Postinstallation 쪽 천천히 다시 해보니까 되네요.
제 생각엔 Post Installation 부분에 4~5번 부분을 다시 한번 해보시는게 좋을 것 같습니다.

**Comment by heyman333** [comment]
@newKeating 위의  확인해 보시고 혹시 문제가 있으면 다시 이슈 생성 부탁 드리겠습니다~
