### ISSUE TITLE
Access Token 만료 여부는 어떻게 확인 할 수 있나요?

### ISSUE THREAD

**Issue by dinidev** [react-native-seoul/react-native-kakao-login#76]
### Version of kakao-login libraries

- react-native-seoul/kakao-login: ^1.0.1-rc2

### Version of react-native

- react-native": 0.60.5

### Platforms you faced the error (IOS or Android or both?)

- Both

### Expected behavior

- 1회 로그인으로 사용자 로그인 세션을 유지하고자 합니다.
- 최초 로그인 시 토큰을 앱 내에 저장하고, 앱을 실행할 때 AccessToken의 만료 여부를 확인하고, 이를 갱신하기 위해 RefreshToken을 이용하고자 합니다.
- 지금까지 확인한 바로는 Kakao REST API에서는 AccessToken 만으로 Refresh Token을 얻을 수 없었습니다.

### Actual behavior

- Back-end 서비스에서 Kakao REST-API 를 이용하여 이 기능을 구현하고자 합니다.
- SDK에서 제공하는 AccessToken 만료에 대한 고민을 하지 않아도 되나요?
- 만약 그렇지 않다면, 로그인 상태를 유지하기 위해서 어떻게 처리해야 하는지 조언을 부탁 드리고자 합니다.

### Tested environment (Emulator? Real Device?)

- 해당사항 없습니다.
- 감사합니다. :D

**Comment by heyman333** [comment]
현재는 `accessToken`만 가져오도록 구성되어 있는데 다음처럼 모든 프로퍼티를 가져올 수 있도록 추후에 수정 하겠습니다~ 

괜찮으시다면 `pr`을 보내주셔도 됩니다!
```
accessToken
카카오 API를 이용하여 특정 사용자의 리소스에 접근하기 위한 OAuth 토큰.

accessTokenExpiresAt
accessToken이 만료되는 시각. 네이티브 앱키로 요청한 accessToken 기본 만료시간: 12시간.

refreshToken
accessToken을 갱신하기 위한 토큰.

refreshTokenExpiresAt
refreshToken이 만료되는 시각. 네이티브 앱키로 요청한 refreshToken 기본 만료시간: 30일.

scopes
현재 로그인된 사용자가 동의한 scope 목록
```

**Comment by dinidev** [comment]
코드를 추가하고 있었는데 빠른 대응 덕분에 바로 적용할 수 있겠네요.
감사합니다. :D

**Comment by heyman333** [comment]
@dinidev 네 혹시 더 추가할 내용이나 수정사항 생기면 언제든지 `PR` 날려주세요~
