### ISSUE TITLE
README에 적힌대로 1.3.8 버전을 설치할 수 없습니다.

### ISSUE THREAD

**Issue by chungheepark** [react-native-seoul/react-native-kakao-login#79]
### Version of kakao-login libraries

1.3.8

### Version of react-native

59.9

### Platforms you faced the error (IOS or Android or both?)

both

### Expected behavior

설치되어야 함

### Actual behavior

package.json

```json
{
...
"react-native-kakao-logins": "^1.3.8
...
}
```

```shell
$ npm install

npm ERR! code EISGIT
npm ERR! path /Users/choong/dev/cojam-rn/node_modules/react-native-kakao-logins
npm ERR! git /Users/choong/dev/cojam-rn/node_modules/react-native-kakao-logins: Appears to be a git repo or submodule.
npm ERR! git     /Users/choong/dev/cojam-rn/node_modules/react-native-kakao-logins
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

60버전으로 올릴 수 없습니다. 1.3.8 버전을 사용해야 합니다.
git repository 자체가 없어졌습니까?
아니면 1.3.8 버전을 어디서 다운받을 수 있습니까?

### Tested environment (Emulator? Real Device?)

OSX both

**Comment by chungheepark** [comment]
npm에 있는 버전들입니다.

2.1.0
2.0.0
1.0.1-rc2
1.0.0-rc2
1.0.0-rc1

README를 업데이트해야 합니까? 아니면 제가 1.0.1-rc2를 사용해야 합니까?

**Comment by heyman333** [comment]
문서에 잘못 표시를 해놨었네요 혼란을 드려서 죄송합니다 
package.json에서 `"react-native-kakao-logins": "^1.3.8`를 지우고
```bash
yarn add react-native-kakao-logins@1.3.8
#OR
npm install  react-native-kakao-logins@1.3.8
```
로 다시 설치 해보시기 바랍니다~

**Comment by chungheepark** [comment]
예 반복 테스트 해서 결과 확인 했습니다. 잘 설치 되네요.
감사합니다.

**Comment by hyochan** [comment]
yarn add @react-native-seoul/kakao-login 으로 레포가 이전되었습니다~
