### ISSUE TITLE
에뮬레이터에서 배포용 apk로 카카오톡 로그인이 안됩니다.

### ISSUE THREAD

**Issue by Arthur-ZB** [react-native-seoul/react-native-kakao-login#82]
### Version of kakao-login libraries

1.3.0

### Version of react-native

0.60.4

### Platforms you faced the error (IOS or Android or both?)

android

### Expected behavior

Emulator에 실배포용 apk를 설치 후 카카오톡 로그인후 callback 와서 로그인이 되야 합니다,
### Actual behavior

Emulator에 실배포용 apk를 설치 후 카카오톡 로그인인 안됩니다.

### Tested environment (Emulator? Real Device?)
Emulator

**Comment by heyman333** [comment]
디버그 모드에서는 되는 로그인이 릴리즈 모드에서는 안된다는 말씀이시죠?

안드로이드 keystore는 총 아래와 같이 3개 종류가 있습니다.
`디버그용 키어` `릴리즈용 키` `플레이스토어 에서 등록한 키`

이 3개가 카카오 개발자 페이지에 다 모두 설정이 되어있는지 한번 확인해주시고,
최신버전(2.1.0v)의 라이브러리를 사용 할것을 권장 드립니다.

**Comment by heyman333** [comment]
추가적으로 안드로이드 스튜디오 로그캣을 보면 카카오 API에서 던져주는 로그메세지를 확인 할 수 있습니다.
그쪽 메세지를 한번 확인해 보시고 올려주시면 더 도움이 될 것 같네요~

**Comment by Arthur-ZB** [comment]
AUTHORIZATION_FAILED: invalid android_key_hash or ios_bundle_id or web_site_url
이런 에러가 발생합니다.
동일한 keystore를 사용 중입니다.

**Comment by Arthur-ZB** [comment]
다른 원인을 찾았습니다. 이슈 닫겠습니다.

**Comment by seyeon-kim** [comment]
같은 이슈가 발생하였습니다. 혹시 어떻게 해결하셨는지 알 수 있을까요?

> AUTHORIZATION_FAILED: invalid android_key_hash or ios_bundle_id or web_site_url
> 이런 에러가 발생합니다.
> 동일한 keystore를 사용 중이며 동일한 apk가 실제 단말에서는 정상적으로 로그인됩니다.

**Comment by Jin-seop** [comment]
@Arthur-ZB 
같은 이슈가 발생했는데 어떻게 해결했는지 알 수 있을까요?
