### ISSUE TITLE
안드로이드 빌드시 오류

### ISSUE THREAD

**Issue by sj602** [react-native-seoul/react-native-kakao-login#84]
### Version of kakao-login libraries

"@react-native-seoul/kakao-login": "^2.1.0",

### Version of react-native

"react-native": "0.61.2",

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior
정상 빌드

### Actual behavior

react-native run-android시 아래와 같은 에러가 발생합니다.

ERROR: The project name '@react-native-seoul/kakao-login' must not contain any of the following characters: [/, \, :, <, >, ", ?, *, |]. Set the 'rootProject.name' or adjust the 'include' statement (see https://docs.gradle.org/5.5/dsl/org.gradle.api.initialization.Settings.html#org.gradle.api.initialization.Settings:include(java.lang.String[]) for more details).

### Tested environment (Emulator? Real Device?)

에뮬레이터

**Comment by heyman333** [comment]
번거로우시겠지만 정상적으로 실행이 되는지 확인만 해보기 위해 
프로젝트를 새로 생성해서 한번 더 시도 가능할가요?

제가 테스트 해볼떄는 문제없이 빌드가 잘 되네요ㅎㅎ

https://stackoverflow.com/questions/54529571/the-project-name-mapbox-react-native-mapbox-gl-must-not-contain-any-of-the-fo

**Comment by minhoyooDEV** [comment]
저도 같은증상입니다.

**Comment by heyman333** [comment]
@minhoyooDEV 설치는 오토로 진행하신거죠?

**Comment by minhoyooDEV** [comment]
> @minhoyooDEV 설치는 오토로 진행하신거죠?

react-native init testProject
yarn add @react-native-seoul/kakao-login
yarn android

한후 다음과 같습니다

$ react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 883 file(s) to forward-jetify. Using 12 workers...
info JS server already running.
info Installing the app...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.kakao.sdk:usermgmt:1.23.0.
     Searched in the following locations:
       - file:/Users/minhoyoo/.m2/repository/com/kakao/sdk/usermgmt/1.23.0/usermgmt-1.23.0.pom
       - file:/Users/minhoyoo/.m2/repository/com/kakao/sdk/usermgmt/1.23.0/usermgmt-1.23.0.jar
       - file:/Users/minhoyoo/Documents/TestFolder/tttt/node_modules/react-native/android/com/kakao/sdk/usermgmt/1.23.0/usermgmt-1.23.0.pom
       - file:/Users/minhoyoo/Documents/TestFolder/tttt/node_modules/react-native/android/com/kakao/sdk/usermgmt/1.23.0/usermgmt-1.23.0.jar
       - file:/Users/minhoyoo/Documents/TestFolder/tttt/node_modules/jsc-android/dist/com/kakao/sdk/usermgmt/1.23.0/usermgmt-1.23.0.pom
       - file:/Users/minhoyoo/Documents/TestFolder/tttt/node_modules/jsc-android/dist/com/kakao/sdk/usermgmt/1.23.0/usermgmt-1.23.0.jar
       - https://dl.google.com/dl/android/maven2/com/kakao/sdk/usermgmt/1.23.0/usermgmt-1.23.0.pom
       - https://dl.google.com/dl/android/maven2/com/kakao/sdk/usermgmt/1.23.0/usermgmt-1.23.0.jar
       - https://jcenter.bintray.com/com/kakao/sdk/usermgmt/1.23.0/usermgmt-1.23.0.pom
       - https://jcenter.bintray.com/com/kakao/sdk/usermgmt/1.23.0/usermgmt-1.23.0.jar
       - https://jitpack.io/com/kakao/sdk/usermgmt/1.23.0/usermgmt-1.23.0.pom
       - https://jitpack.io/com/kakao/sdk/usermgmt/1.23.0/usermgmt-1.23.0.jar
     Required by:
         project :app > project :@react-native-seoul_kakao-login

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.kakao.sdk:usermgmt:1.23.0.
     Searched in the following locations:
       - file:/Users/minhoyoo/.m2/repository/com/kakao/sdk/usermgmt/1.23.0/usermgmt-1.23.0.pom
       - file:/Users/minhoyoo/.m2/repository/com/kakao/sdk/usermgmt/1.23.0/usermgmt-1.23.0.jar
       - file:/Users/minhoyoo/Documents/TestFolder/tttt/node_modules/react-native/android/com/kakao/sdk/usermgmt/1.23.0/usermgmt-1.23.0.pom
       - file:/Users/minhoyoo/Documents/TestFolder/tttt/node_modules/react-native/android/com/kakao/sdk/usermgmt/1.23.0/usermgmt-1.23.0.jar
       - file:/Users/minhoyoo/Documents/TestFolder/tttt/node_modules/jsc-android/dist/com/kakao/sdk/usermgmt/1.23.0/usermgmt-1.23.0.pom
       - file:/Users/minhoyoo/Documents/TestFolder/tttt/node_modules/jsc-android/dist/com/kakao/sdk/usermgmt/1.23.0/usermgmt-1.23.0.jar
       - https://dl.google.com/dl/android/maven2/com/kakao/sdk/usermgmt/1.23.0/usermgmt-1.23.0.pom
       - https://dl.google.com/dl/android/maven2/com/kakao/sdk/usermgmt/1.23.0/usermgmt-1.23.0.jar
       - https://jcenter.bintray.com/com/kakao/sdk/usermgmt/1.23.0/usermgmt-1.23.0.pom
       - https://jcenter.bintray.com/com/kakao/sdk/usermgmt/1.23.0/usermgmt-1.23.0.jar
       - https://jitpack.io/com/kakao/sdk/usermgmt/1.23.0/usermgmt-1.23.0.pom
       - https://jitpack.io/com/kakao/sdk/usermgmt/1.23.0/usermgmt-1.23.0.jar
     Required by:
         project :app > project :@react-native-seoul_kakao-login

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

    at checkExecSyncError (child_process.js:616:11)
    at execFileSync (child_process.js:634:13)
    at runOnAllDevices (/Users/minhoyoo/Documents/TestFolder/tttt/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at buildAndRun (/Users/minhoyoo/Documents/TestFolder/tttt/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:158:41)
    at then.result (/Users/minhoyoo/Documents/TestFolder/tttt/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:125:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by heyman333** [comment]
@minhoyooDEV 음 정보 감사합니다. 수정하도록 하겠습니다. 혹시 해결방법을 찾으신다면 pr을 보내주시면 감사하겠습니다 👍

**Comment by minhoyooDEV** [comment]
pacakge.json입니다

{
  "name": "tttt",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-seoul/kakao-login": "^2.1.0",
    "react": "16.9.0",
    "react-native": "0.61.4"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by heyman333** [comment]
@minhoyooDEV @sj602 지금 확인해보니 카카오 SDK버전을 못찾아서 빌드에 실패하는 것 같네요
`Could not find com.kakao.sdk:usermgmt:1.23.0`
설치 방법이 바뀌었는지 다시 문서를 확인하고 수정하겠습니다.

**Comment by minhoyooDEV** [comment]
빠른피드백이네요!! 감사합니다!

**Comment by heyman333** [comment]
@minhoyooDEV @sj602
아이고 제가 실수를 했네요...ㅎㅎ.ㅎㅎ
https://github.com/react-native-seoul/react-native-kakao-login#android-1
혹시 위부분을 누락하진 않았는지 다시 한번 확인부탁 드릴게요
이전에 오타가 있어서 수정해서 README에 반영 했고, 바로 npm에 `2.2.1`로 배포 하겠습니다~

**Comment by heyman333** [comment]
2.1.1에 반영되었습니다.

**Comment by heyman333** [comment]
@sj602 
안녕하세요 @sj602 님 아무래도 설치를 메뉴얼로 진행하셨나보네요 안드로이드 메뉴얼 설치중에 특수문자가 들어가면 안되는 사실을 오늘 테스중에 알았습니다 ㅠ.ㅠ
설치 문서를 다시 업데이트 했으니 확인 부탁드립니다~

**Comment by sj602** [comment]
제가 깜빡 잊고 답장을 못 드렸네요!
지금은 덕분에 해결했습니다 ㅎㅎ
늦게나마 감사드립니다 :)
