### ISSUE TITLE
README에 카카오 maven 주소가 잘못되어 있습니다.

### ISSUE THREAD

**Issue by chungheepark** [react-native-seoul/react-native-kakao-login#85]
### Version of react-native

^2.1.0

### Platforms you faced the error (IOS or Android or both?)

android

### Expected behavior

안드로이드 빌드가 정상적으로 되어야함

### Actual behavior

gradle 빌드시 illegar character... 오류가 발생

### Tested environment (Emulator? Real Device?)

실제기기: galaxy s7

### 조치:

as-is:

```gradle
maven { url 'http://devrepo.kakao.com:8088/ +nexus/content/groups/public/' }
```

to-be:

```gradle
maven { url 'http://devrepo.kakao.com:8088/nexus/content/groups/public/' }
```

**Comment by heyman333** [comment]
감사합니다 다음 릴리즈때 수정하겠습니다~

**Comment by heyman333** [comment]
2.1.1에 반영되었습니다.
