### ISSUE TITLE
안드로이드에서 file path error 

### ISSUE THREAD

**Issue by kirhim** [react-native-seoul/react-native-kakao-login#92]
ios에서는 잘되는데 안드로이드에 설치시

ERROR: The modules ['@react-native-seoul_kakao-login', 'react-native-seoul-kakao-login'] point to the same directory in the file system.

이렇게 나옵니다.  .iml 파일 지우고 다시 import 했는데도 계속이러네요.

**Comment by heyman333** [comment]
@kirhim 안드로이드 매뉴얼로 설치 하셨나요?
이슈템플릿도 같이 작성해서 수정 해주시면 감사하겠습니다~

**Comment by heyman333** [comment]
위에 적어주신 내용을 보니까 react-native-seoul_kakao-login 에서 `-` 대신에 `_`가 쓰인것 같네요?
다시 한번 설치 방벙을 확인해 보시고 안되면 다시 코멘트 달아주시기 바랄게요~
