### ISSUE TITLE
사용자 정보 요청시 phone number 획득 가능 여부

### ISSUE THREAD

**Issue by heyman333** [react-native-seoul/react-native-kakao-login#95]
### Version of kakao-login libraries

2.2.0

### Version of react-native

0.60.5

### Platforms you faced the error (IOS or Android or both?)

both

### Expected behavior

유저 핸드폰번호를 획득합니다.

### Actual behavior

유저 핸드폰 번호가 넘어올 수 있는지 궁금합니다.

### Tested environment (Emulator? Real Device?)

n / a

안녕하세요 @Bang9 님 전에 PR을 주실때(https://github.com/react-native-seoul/react-native-kakao-login#params-in-result-when-getprofile), 유저 동의하에 phone_number를 가져올 수 있도록 수정 해주신거같은데, 제가 카카오 문서를 찾아보니 유저의 핸드폰 번호를 얻을 수 있는 방법은 딱히 없어보이네요...

혹시 실제로 유저 핸드폰 번호를 받아서 사용중이신가요?

**Comment by Bang9** [comment]
@heyman333 안녕하세요 답변이 늦었네요 ㅎㅎ

핸드폰 번호 항목에 대한 공식 문서는 아래 사진과 같이 설명돼있습니다.
해당 권한이 없다면 null, 권한이 있다면 해당 값을 반환하게 됩니다.
(여기서 제휴를 통한 권한을 얻기 위해서는, biz 앱 등록 및 kakao sync 등 추가적인 작업이 필요합니다.)

![image](https://user-images.githubusercontent.com/26326015/71704938-5b12a080-2e20-11ea-8612-5a2fe49d8777.png)

---

이 제휴가 완료되면 아래 스크린샷과 같이 동의항목에 요구가능한 권한이 추가가 됩니다.
(동의항목의 경우에는 `KakaoDevelopers > 내 앱 > 설정 > 사용자 관리` 에서 추가하실 수 있습니다.)

![image](https://user-images.githubusercontent.com/26326015/71705036-d83e1580-2e20-11ea-8b90-d5e9da4305ad.png)


---

제휴 이후에는 자동으로 권한이 추가가 되지만, 제휴 이전의 유저들에게 권한을 요청하고 정보를 받기 위해서는
동적 동의 과정이 필요합니다. (동적 동의는 따로 구현하지 않았습니다.)

https://developers.kakao.com/docs/ios/user-management#동적동의
https://developers.kakao.com/docs/android/user-management#동적동의

**Comment by heyman333** [comment]
@Bang9 아 결국 biz앱에 등록을 해야 되는거군요...친절한 답변 감사드립니다!

**Comment by hyochan** [comment]
@Bang9 많이 문의주셨던 부분인데 알아봐주셔서 감사드립니다! 더불어 다른 레포에도 활발히 서포트해주셔서 정말 감사드립니다 🙏 밋업에서 한번 뵈었으면 좋겠습니다 😄

**Comment by Bang9** [comment]
@hyochan 팀원분이 최근 밋업에 참여하셨던데, 저도 한번 기회를봐서 참여해보도록 하겠습니다. 감사합니다 ㅎㅎ :)
